---
title: "Examples of uses of the data"
toc: false
---

This page includes links to news articles and, soon, scholarly articles that use data posted by the Deportation Data Project to illustrate how the data can be used by journalists and scholars.

## News articles and blog posts

* [Más de dos mil quinientas personas detenidas por ICE en Tennessee en tan sólo seis meses](https://www.telemundonashville.com/, 2025/07/04/ms-de-dos-mil-quinientas-personas-detenidas-por-ice-en-tennessee-en-tan-slo-seis-meses/) ([archived](https://web.archive.org/save/https://www.telemundonashville.com/, 2025/07/04/ms-de-dos-mil-quinientas-personas-detenidas-por-ice-en-tennessee-en-tan-slo-seis-meses/)), by Anel Flores, *Telemundo Nashville*, July 4, 2025.

* [Two dozen Hmong Minnesotans await deportation to Laos after new round of ICE arrests](https://www.startribune.com/hmong-minnesotans-face-deportation-laos-ice-arrests/601385285) ([archived](https://web.archive.org/save/https://www.startribune.com/hmong-minnesotans-face-deportation-laos-ice-arrests/601385285)), by Reid Forgrave and Rachel Hutton, *Star Tribune*, July 4, 2025.

* [Immigration data shows surge in detentions and deportations in Iowa](https://www.kcrg.com/, 2025/07/03/immigration-data-shows-surge-detentions-deportations-iowa/) ([archived](https://web.archive.org/save/https://www.kcrg.com/, 2025/07/03/immigration-data-shows-surge-detentions-deportations-iowa/)), by Brian Tabick, *KCRG-TV9*, July 3, 2025.

* [ICE increasingly targets undocumented migrants with no criminal record](https://www.washingtonpost.com/immigration/, 2025/07/03/ice-arrests-migrants-criminal-record-numbers/) ([archived](https://web.archive.org/save/https://www.washingtonpost.com/immigration/, 2025/07/03/ice-arrests-migrants-criminal-record-numbers/)), by Emmanuel Martinez, Marianne LeVine and Álvaro Valiño, *The Washington Post*, July 3, 2025.

* [Sharpest growth in ICE detention population is among people with no criminal convictions](https://www.npr.org/, 2025/07/03/nx-s1-5454891/sharpest-growth-in-ice-detention-population-people-with-no-criminal-convictions) ([archived](https://web.archive.org/save/https://www.npr.org/, 2025/07/03/nx-s1-5454891/sharpest-growth-in-ice-detention-population-people-with-no-criminal-convictions)), by Jasmine Garsd, *NPR*, July 3, 2025.

* [ICE arrests are up in Connecticut. Here’s where migrants were apprehended](https://www.vermontpublic.org/, 2025-07-03/ice-arrests-connecticut-where-migrants-were-apprehended) ([archived](https://web.archive.org/save/https://www.vermontpublic.org/, 2025-07-03/ice-arrests-connecticut-where-migrants-were-apprehended)), by Jim Haddadin, *Vermont Public*, July 3, 2025.

* [Hawaii lawmakers demand immigration-arrest briefings](https://www.staradvertiser.com/, 2025/07/03/hawaii-news/hawaii-lawmakers-demand-immigration-arrest-briefings/) ([archived](https://web.archive.org/save/https://www.staradvertiser.com/, 2025/07/03/hawaii-news/hawaii-lawmakers-demand-immigration-arrest-briefings/)), by Dan Nakaso, *Honolulu Star-Advertiser*, July 3, 2025.

* [Here’s how much ICE arrests have risen in Tennessee since Trump took office](https://www.yahoo.com/news/much-ice-arrests-risen-tennessee-193409670.html) ([archived](https://web.archive.org/save/https://www.yahoo.com/news/much-ice-arrests-risen-tennessee-193409670.html)), by Melissa Brown, *The Tennessean*, July 3, 2025.

* [Immigration crackdown ripples through economy](https://www.axios.com/, 2025/07/02/trump-immigration-crackdown-economy) ([archived](https://web.archive.org/save/https://www.axios.com/, 2025/07/02/trump-immigration-crackdown-economy)), by Emily Peck, *Axios*, July 2, 2025.

* [Have ICE arrests, deportations in Iowa climbed under President Trump? What the numbers say](https://eu.desmoinesregister.com/story/news/, 2025/07/02/ice-raids-data-increasing-rate-of-arrests-deportations-iowa/84390913007/) ([archived](https://web.archive.org/save/https://eu.desmoinesregister.com/story/news/, 2025/07/02/ice-raids-data-increasing-rate-of-arrests-deportations-iowa/84390913007/)), by Tim Webber, *Des Moines Register*, July 2, 2025.

* [ICE agents in Midwest jurisdiction recently arresting more who have no prior criminal convictions](https://abc7chicago.com/post/ice-agents-midwest-jurisdiction-recently-arresting-more-have-no-prior-criminal-convictions-charges/16908927/) ([archived](https://web.archive.org/save/https://abc7chicago.com/post/ice-agents-midwest-jurisdiction-recently-arresting-more-have-no-prior-criminal-convictions-charges/16908927/)), by Liz Nagy, Barb Markoff, Christine Tressel and Tom Jones, *ABC7 Chicago*, July 2, 2025.

* [Estos son los 10 estados en donde más detienen a migrantes en Estados Unidos: ICE adoptó métodos más agresivos](https://www.eltiempo.com/mundo/eeuu-y-canada/estos-son-los-10-de-estados-en-donde-mas-detienen-a-migrantes-en-estados-unidos-ice-adopto-metodos-mas-agresivos-3468126) ([archived](https://web.archive.org/save/https://www.eltiempo.com/mundo/eeuu-y-canada/estos-son-los-10-de-estados-en-donde-mas-detienen-a-migrantes-en-estados-unidos-ice-adopto-metodos-mas-agresivos-3468126)), by Sergio Gómez Maseri, *El Tiempo*, July 2, 2025.

* [Majority of ICE arrestees in Tennessee have criminal record, new ICE data says](https://www.wkrn.com/news/tennessee-politics/tn-ice-arrests-data/) ([archived](https://web.archive.org/save/https://www.wkrn.com/news/tennessee-politics/tn-ice-arrests-data/)), *WKRN News 2* staff, July 2, 2025.

* [Trump vowed to deport the ‘worst of the worst’ — but new data shows a shift to also arresting non-criminals](https://abcnews.go.com/US/trump-vowed-deport-worst-worst-new-data-shows/story?id=123287810) ([archived](https://web.archive.org/save/https://abcnews.go.com/US/trump-vowed-deport-worst-worst-new-data-shows/story?id=123287810)), by Laura Romero, Armando Garcia and Frank Esposito, *ABC News*, July 1, 2025.

* [Immigration arrests increase in Ohio and Kentucky](https://eu.cincinnati.com/story/news/politics/, 2025/07/01/immigration-arrests-increase-in-ohio-and-kentucky/84415726007/) ([archived](https://web.archive.org/save/https://eu.cincinnati.com/story/news/politics/, 2025/07/01/immigration-arrests-increase-in-ohio-and-kentucky/84415726007/)), by Annie Goldman, *Cincinnati Enquirer*, July 1, 2025.

* [NYC immigration arrests jump 31%, testing America’s largest sanctuary city](https://www.bloomberg.com/news/articles/, 2025-07-01/new-york-city-immigration-arrests-jump-31-putting-sanctuary-city-to-test) ([archived](https://web.archive.org/save/https://www.bloomberg.com/news/articles/, 2025-07-01/new-york-city-immigration-arrests-jump-31-putting-sanctuary-city-to-test)), by Katia Porzecanski, *Bloomberg News*, July 1, 2025.

* [Trump’s immigration raids spark outrage in Los Angeles](https://www.latimes.com/california/story/, 2025-07-01/trump-immigration-raids-los-angeles) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/, 2025-07-01/trump-immigration-raids-los-angeles)), by David Zahniser, Brittny Mejia and Noah Goldberg, *Los Angeles Times*, July 1, 2025.

* [As immigrant arrests rise, Hawai‘i political leaders condemn ICE tactics](https://www.civilbeat.org/, 2025/07/immigrant-arrests-rise-hawaii-political-leaders-condemn-ice-tactics/) ([archived](https://web.archive.org/save/https://www.civilbeat.org/, 2025/07/immigrant-arrests-rise-hawaii-political-leaders-condemn-ice-tactics/)), by Jeremy Hay and Matthew Leonard, *Honolulu Civil Beat*, July 1, 2025.

* [‘Alligator Alcatraz’: Trump’s swamp jail to aid record migrant crackdown](https://www.telegraph.co.uk/us/news/, 2025/07/01/donald-trump-immigration-crackdown-charts-data-florida/) ([archived](https://web.archive.org/save/https://www.telegraph.co.uk/us/news/, 2025/07/01/donald-trump-immigration-crackdown-charts-data-florida/)), by Rozina Sabur, *The Telegraph*, July 1, 2025.

* [ICE detentions of non-criminal immigrants spike; about 8 % have violent convictions, analysis shows](https://www.cbsnews.com/news/ice-detentions-non-criminal-immigrants-violent-crime-convictions-analysis/) ([archived](https://web.archive.org/save/https://www.cbsnews.com/news/ice-detentions-non-criminal-immigrants-violent-crime-convictions-analysis/)), by Julia Ingram, *CBS News*, June 30, 2025.

* [Asylum seekers are being arrested during mandatory ICE check-ins](https://www.portlandmercury.com/news/, 2025/06/30/47900446/asylum-seekers-are-being-arrested-during-mandatory-ice-check-ins) ([archived](https://web.archive.org/save/https://www.portlandmercury.com/news/, 2025/06/30/47900446/asylum-seekers-are-being-arrested-during-mandatory-ice-check-ins)), by Courtney Vaughn, *Portland Mercury*, June 30, 2025.

* [‘It’s a prison’: Asylum seekers in Houston detention centers face longer stays, no clear answers](https://www.houstonchronicle.com/news/houston-texas/immigration/article/houston-asylum-seekers-face-longer-detention-ice-20381512.php) ([archived](https://web.archive.org/save/https://www.houstonchronicle.com/news/houston-texas/immigration/article/houston-asylum-seekers-face-longer-detention-ice-20381512.php)), by Sam González Kelly and Ava Hu, *Houston Chronicle*, June 29, 2025.

* [Immigration enforcement ‘hit home’ for Trump supporter worried about ‘little buddy’ ICE detained](https://nebraskaexaminer.com/, 2025/06/29/immigration-enforcement-hit-home-for-trump-supporter-worried-about-little-buddy-ice-detained/) ([archived](https://web.archive.org/save/https://nebraskaexaminer.com/, 2025/06/29/immigration-enforcement-hit-home-for-trump-supporter-worried-about-little-buddy-ice-detained/)), by Cindy Gonzalez, *Nebraska Examiner*, June 29, 2025.

* [Newly revealed data shows the scale of President Trump’s immigration crackdown](https://lavocedinewyork.com/en/news/, 2025/06/28/newly-revealed-data-shows-the-scale-of-trumps-immigration-crackdown/) ([archived](https://web.archive.org/save/https://lavocedinewyork.com/en/news/, 2025/06/28/newly-revealed-data-shows-the-scale-of-trumps-immigration-crackdown/)), by David Mazzucchi, *La Voce di New York*, June 28, 2025.

* [Las detenciones migratorias se han duplicado en 38 estados desde que Trump asumió](https://www.youtube.com/watch?v=qTYV4cgkrlo) ([archived](https://web.archive.org/save/https://www.youtube.com/watch?v=qTYV4cgkrlo)), *Telemundo*, June 28, 2025.

* [ICE arrests have risen sharply in every state since Trump. Here are the numbers.](https://www.nytimes.com/interactive/, 2025/06/27/us/ice-arrests-trump.html) ([archived](https://web.archive.org/save/https://www.nytimes.com/interactive/, 2025/06/27/us/ice-arrests-trump.html)), by Albert Sun, *The New York Times*, June 27, 2025.

* [Trump says he’s deporting ‘the worst of the worst.’ Here’s what California ICE data really shows](https://www.sfchronicle.com/bayarea/article/ice-arrest-immigrant-california-20395589.php) ([archived](https://web.archive.org/save/https://www.sfchronicle.com/bayarea/article/ice-arrest-immigrant-california-20395589.php)), by Christian Leonard, *San Francisco Chronicle*, June 27, 2025.

* [ICE won’t say how many people it’s arrested in Maine](https://www.bangordailynews.com/, 2025/06/27/bangor/bangor-police-courts/ice-wont-say-how-many-people-its-arrested-in-maine/) ([archived](https://web.archive.org/save/https://www.bangordailynews.com/, 2025/06/27/bangor/bangor-police-courts/ice-wont-say-how-many-people-its-arrested-in-maine/)), by Marie Weidmayer, *Bangor Daily News*, June 27, 2025.

* [More than half of those arrested by ICE in CT had pending criminal charges, or convictions](https://www.wfsb.com/, 2025/06/27/more-than-half-those-arrested-by-ice-ct-had-pending-criminal-charges-or-convictions/) ([archived](https://web.archive.org/save/https://www.wfsb.com/, 2025/06/27/more-than-half-those-arrested-by-ice-ct-had-pending-criminal-charges-or-convictions/)), by Sam Smink, *WFSB 3 Connecticut*, June 27, 2025.

* [The end of Narciso’s American dream: The brutal arrest of a Mexican gardener shocks Santa Ana](https://english.elpais.com/usa/, 2025-06-27/the-end-of-narcisos-american-dream-the-brutal-arrest-of-a-mexican-gardener-shocks-santa-ana.html) ([archived](https://web.archive.org/save/https://english.elpais.com/usa/, 2025-06-27/the-end-of-narcisos-american-dream-the-brutal-arrest-of-a-mexican-gardener-shocks-santa-ana.html)), by Luis Pablo Beauregard, *El País*, June 27, 2025.

* [New data shows that over half of those detained by ICE in Los Angeles have no criminal history](https://lamag.com/news/new-data-shows-that-over-half-of-those-detained-by-ice-in-los-angeles-have-no-criminal-history) ([archived](https://web.archive.org/save/https://lamag.com/news/new-data-shows-that-over-half-of-those-detained-by-ice-in-los-angeles-have-no-criminal-history)), by Ava Mitchell, *Los Angeles Magazine*, June 27, 2025.

* [Catholic bishop criticizes ICE raids, calls for respectful immigration reform](https://premierchristian.news/en/news/article/catholic-bishop-criticises-ice-raids) ([archived](https://web.archive.org/save/https://premierchristian.news/en/news/article/catholic-bishop-criticises-ice-raids)), *Premier Christian News*, June 27, 2025.

* [35 % of New York City ICE arrests aren’t criminals, new data shows](https://abc7ny.com/post/immigration-enforcement-35-nyc-ice-arrests-arent-criminals-according-newly-released-data/16855965) ([archived](https://web.archive.org/save/https://abc7ny.com/post/immigration-enforcement-35-nyc-ice-arrests-arent-criminals-according-newly-released-data/16855965)), by Dan Krauth, *ABC7 New York*, June 27, 2025.

* [Artesia’s Little India feels widespread impact of immigration raids](https://abc7.com/post/artesias-little-india-feels-widespread-impact-of-immigration-raids/16857210/) ([archived](https://web.archive.org/save/https://abc7.com/post/artesias-little-india-feels-widespread-impact-of-immigration-raids/16857210/)), by David González, *ABC7 Los Angeles*, June 27, 2025.

* [Asian American leaders urge their communities to stand by Latinos, denounce ICE raids](https://www.latimes.com/california/story/, 2025-06-26/asian-american-leaders-urge-communities-to-stand-by-latinos-denounce-ice-raids) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/, 2025-06-26/asian-american-leaders-urge-communities-to-stand-by-latinos-denounce-ice-raids)), by Melissa Gomez, *Los Angeles Times*, June 26, 2025.

* [ICE set to arrest a record 35,000 immigrants in June; daily quotas are political – not practical](https://austinkocher.substack.com/p/ice-set-to-arrest-a-record-35000) ([archived](https://web.archive.org/save/https://austinkocher.substack.com/p/ice-set-to-arrest-a-record-35000)), by Austin Kocher, *Substack*, June 25, 2025.

* [Majority arrested by ICE in L.A. area have no criminal history, data shows](https://abc7.com/post/more-half-arrested-ice-la-area-have-no-criminal-history-data-shows/16850562/) ([archived](https://web.archive.org/save/https://abc7.com/post/more-half-arrested-ice-la-area-have-no-criminal-history-data-shows/16850562/)), by Kevin Ozebek, *ABC7 Los Angeles*, June 25, 2025.

* [A close look at ICE arrest data from the Deportation Data Project](https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from?triedRedirect=true) ([archived](https://web.archive.org/save/https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from?triedRedirect=true)), by Austin Kocher, *Substack*, June 25, 2025.

* [Most nabbed in L.A. raids were men with no criminal conviction, picked up off the street](https://www.latimes.com/california/story/, 2025-06-24/detention-centers-swell-with-immigrants-with-no-criminal-record) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/, 2025-06-24/detention-centers-swell-with-immigrants-with-no-criminal-record)), by Rachel Uranga, *Los Angeles Times*, June 24, 2025.

* [How Trump has targeted new groups for deportation](https://www.nytimes.com/interactive/, 2025/05/21/us/trump-immigration-policy.html) ([archived](https://web.archive.org/save/https://www.nytimes.com/interactive/, 2025/05/21/us/trump-immigration-policy.html)), by Ashley Wu and Albert Sun, *The New York Times*, May 21, 2025.

* [Addicted to ICE](https://www.bloomberg.com/features/, 2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true) ([archived](https://web.archive.org/save/https://www.bloomberg.com/features/, 2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true)), by Rachel Adams-Heard, Polly Mosendz and Fola Akinnibi, *Bloomberg*, May 12, 2025.

* [The rising cost of ICE flying immigrants to far-flung detention centers](https://www.bloomberg.com/graphics/, 2025-trump-ice-immigrant-move-costs-taxpayers/) ([archived](https://web.archive.org/save/https://www.bloomberg.com/graphics/, 2025-trump-ice-immigrant-move-costs-taxpayers/)), by Leon Yin, Elena Mejía, Rachel Adams-Heard and Polly Mosendz, *Bloomberg*, May 1, 2025.

* [ICE chief thinks deportation system should be run like Amazon Prime ‘but with human beings’](https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html) ([archived](https://web.archive.org/save/https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html)), by Graig Graziosi, *The Independent*, April 9, 2025.

* [What the data really tells us about Trump’s deportation agenda](https://www.eltimpano.org/newsletter/what-the-data-really-tells-us-about-trumps-deportation-agenda) ([archived](https://web.archive.org/save/https://www.eltimpano.org/newsletter/what-the-data-really-tells-us-about-trumps-deportation-agenda)), by Erica Hellerstein, *El Tímpano*, April 11, 2025.

* [As deportations ramp up, immigrants increasingly fear ICE check-ins: ‘All bets are off’](https://www.theguardian.com/us-news/, 2025/apr/06/deportations-immigrants-ice-trump) ([archived](https://web.archive.org/save/https://www.theguardian.com/us-news/, 2025/apr/06/deportations-immigrants-ice-trump)), by Maanvi Singh and Will Craft, *The Guardian*, April 6, 2025.

* [Trump touted these ICE arrests. Half were already in prison.](https://www.washingtonpost.com/immigration/interactive/, 2025/trump-ice-arrests-prison-immigrants/) ([archived](https://web.archive.org/save/https://www.washingtonpost.com/immigration/interactive/, 2025/trump-ice-arrests-prison-immigrants/)), by Maria Sacchetti and Artur Galocha, *The Washington Post*, April 3, 2025.

* [ICE to release detainee who came to the U.S. to give his brother a kidney](https://www.washingtonpost.com/nation/, 2025/04/02/ice-arrests-venezuelan-kidney-donor/) ([archived](https://web.archive.org/save/https://www.washingtonpost.com/nation/, 2025/04/02/ice-arrests-venezuelan-kidney-donor/)), by Maria Sacchetti, *The Washington Post*, April 2, 2025.
