---
title: Ejemplos de uso de los datos
toc: false
---

Esta página incluye enlaces a artículos de prensa y, próximamente, a artículos académicos que utilizan los datos publicados por el Deportation Data Project para ilustrar cómo pueden utilizarlos los periodistas y los académicos.

## Artículos de prensa

- [Video: 26 Federal Plaza inmigración ICE DHS celdas](https://www.thecity.nyc/2025/07/22/video-26-federal-plaza-immigration-ice-dhs-cells/) por [Autor por determinar], *THE CITY*, 22 de julio de 2025. [Inglés]

- [Cómo Trump ha apuntado a nuevos grupos para la deportación](https://www.nytimes.com/interactive/2025/05/21/us/trump-immigration-policy.html) por Ashley Wu y Albert Sun, *New York Times*, 21 de mayo de 2025. [Inglés]

- [Adictos al ICE](https://www.bloomberg.com/features/2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true) por Rachel Adams-Heard, Polly Mosendz y Fola Akinnibi, *Bloomberg* 12 de mayo de 2025. [Inglés]

- [El creciente coste de los vuelos del ICE a centros de detención lejanos](https://www.bloomberg.com/graphics/2025-trump-ice-immigrant-move-costs-taxpayers/?accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJTdWJzY3JpYmVyR2lmdGVkQXJ0aWNsZSIsImlhdCI6MTc0NjEwNzg1NiwiZXhwIjoxNzQ2NzEyNjU2LCJhcnRpY2xlSWQiOiJTVktYOFNEV1gyUFMwMCIsImJjb25uZWN0SWQiOiJCNTIwMUQ0RjVFMzM0QTNEOEE4QjdDNTBCMkYzNjU4NCJ9.OUyF_xSj6c6TmS_xkDgaDD9zVc0U3_XkmsGyqoyPHjM&leadSource=uverify%20wall) por Leon Yin, Elena Mejía, Rachel Adams-Heard y Polly Mosendz, *Bloomberg* 1 de mayo de 2025. [Inglés]

- [El jefe del ICE cree que el sistema de deportación debería funcionar como Amazon Prime 'pero con seres humanos'](https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html) por Graig Graziosi, *Independent* 9 de abril de 2025. [Inglés]

- [Lo que los datos nos dicen realmente sobre la agenda de deportaciones de Trump](https://www.eltimpano.org/newsletter/what-the-data-really-tells-us-about-trumps-deportation-agenda) por Erica Hellerstein, *El Tímpano* 11 de abril de 2025. [Inglés]

- [A medida que aumentan las deportaciones, los inmigrantes temen cada vez más los controles en el hielo: "Todo está perdido"](https://www.theguardian.com/us-news/2025/apr/06/deportations-immigrants-ice-trump) por Maanvi Singh y Will Craft, *The Guardian* 6 de abril de 2025. [Inglés]

- [Trump promocionó estas detenciones del ICE. La mitad ya estaban en prisión.](https://www.washingtonpost.com/immigration/interactive/2025/trump-ice-arrests-prison-immigrants/) por Maria Sacchetti y Artur Galocha, *Washington Post* 3 de abril de 2025. [Inglés]

- [El ICE liberará al detenido que vino a EE.UU. para donar un riñón a su hermano](https://www.washingtonpost.com/nation/2025/04/02/ice-arrests-venezuelan-kidney-donor/) por Maria Sacchetti, *Washington Post* 2 de abril de 2025. [Inglés]


