---
title: Proyecto de datos sobre deportaciones
toc: false
main-width: 900px
---

<p style="font-size:22px; line-height: 2rem; background-color: #D9E3E8; margin-top:25px; margin-bottom:25px; padding: 20px; border-radius: 5px;">El Proyecto de Datos de Deportación recopila y publica conjuntos de datos anónimos del gobierno de EE.UU. sobre la aplicación de las leyes de inmigración. Recurrimos a la Ley de Libertad de Información para obtener datos directamente del gobierno, y también publicamos datos que el gobierno ha publicado de forma proactiva o en respuesta a solicitudes de otros. Esperamos que estos datos sean utilizados por periodistas, investigadores, abogados y responsables políticos.</p>

Como primer paso, hemos publicado los principales conjuntos de datos que conocemos; en la mayoría de los casos, estos conjuntos de datos están desactualizados. Estamos buscando actualizaciones y las publicaremos a medida que las recibamos.

Publicamos sobre todo [conjuntos de datos individuales](data.html). Los datos a nivel individual son más útiles para quienes tienen experiencia en el análisis de datos, ya que les permiten tomar sus propias decisiones sobre cómo analizarlos.

También proporcionamos [enlaces a proyectos relacionados](related.html) que ofrecen análisis, visualizaciones e informes para periodistas, abogados y el público en general basados en estos conjuntos de datos. Si tiene preguntas o sugerencias sobre los datos, no dude en ponerse en contacto con nosotros.

Agradecemos el trabajo de los demás, y en especial del [Centro de Intercambio de Información sobre el Acceso a los Registros Transaccionales (TRAC)](https://tracreports.org) en la obtención del acceso a muchos de estos conjuntos de datos. Por favor, póngase en contacto con nosotros si ha realizado algún trabajo relevante en este ámbito y podemos hacer más para reconocer sus contribuciones.

::: {.grid}

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}

## Formule una pregunta sobre datos

Díganos si podemos responder a sus preguntas. Si no podemos, le remitiremos a alguien que sí pueda.

[Pregunte a](mailto:deportation_data_questions@law.berkeley.edu){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-lg role="button"}

## Obtener notificaciones de datos

Suscríbase para recibir notificaciones sobre la publicación de datos del Proyecto de Datos de Deportación.

[Únase a](https://groups.google.com/a/law.berkeley.edu/g/deportation_data_updates/about){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-lg role="button"}

:::

::: {.g-col-12 .g-col-md-6 .g-col-lg-6}

## Comparta sus datos

Ponga sus datos al servicio de los demás Si dispone de datos públicos y compartibles sobre la aplicación de las leyes de inmigración procedentes de una solicitud conforme a la FOIA o de la presentación de pruebas en un litigio, nos encantaría publicar sus datos (citándole a usted) o enlazar con su repositorio de datos. Podemos ponerle en contacto con otras personas que puedan crear herramientas visuales a partir de sus datos o ayudar a analizarlos.

[Comparta](mailto:deportation_data_questions@law.berkeley.edu){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-lg role="button"}

:::

:::


