---
title: "Deportation Data Project"
toc: false
main-width: 900px
format:
  html:
    anchor-sections: false
---

::: {.div style = "background-color: #D9E3E8;padding-left: 20px; padding-right:20px; padding-top: 15px; padding-bottom:5px; border-radius: 5px;"}

<p style="font-size:22px; line-height: 2rem">The Deportation Data Project collects and posts public, anonymized U.S. government immigration enforcement datasets. We expect these datasets to be used by journalists, researchers, lawyers, and policymakers.</p>

**Questions about the most recent ICE data release? Please start with our [ICE data FAQ](https://deportationdata.org/docs/ice.html#faq).**

::: {.grid}

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi card-checklist class="me-2" >}} Obtaining 

We obtain immigration enforcement data from the U.S. government, primarily through Freedom of Information Act requests. 

[Explore requests](/foia.html){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi file-earmark-arrow-up class="me-2" >}} Posting

We share datasets that we obtain, that the government posts proactively in response to other requests, and that others share with us.

[Download data](/data.html){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi journal-text class="me-2" >}} Explaining

We document the data we post. We write codebooks and post internal documentation from the agencies.

[Read data guide](/guide.html){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

<!-- grid-->
:::

<!-- div -->
::: 

::: {.div style = "padding-left: 20px; padding-right:20px; padding-top: 15px; padding-bottom:5px"}

::: {.grid}

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi envelope-open class="me-2" >}} Join for updates

Subscribe to receive email notifications of each new data release.

[Subscribe](https://groups.google.com/a/law.berkeley.edu/g/deportation_data_updates/about){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi folder-plus class="me-2" >}} Share your data 

We would love to post or link to your public, shareable data (crediting you).

[Share](mailto:deportation_data_questions@law.berkeley.edu){.btn .btn-outline-primary .btn-sm role="button"} 

:::


::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi chat-dots class="me-2" >}} Ask a question 

Let us know if we can answer your data questions. If we can't, we'll refer you.

[Ask](mailto:deportation_data_questions@law.berkeley.edu){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

:::

<!-- div -->
:::