---
title: Novedades de datos
toc: false
listing:
  id: news-listings
  contents: noticias
  sort: date desc
  type: table
  fields:
  - date
  - title
  categories: false
  filter-ui: false
  sort-ui: false
---

::: {#news-listings}
:::

::: {.callout-note}

## Suscribirse

Suscríbase para recibir estas actualizaciones de datos por correo electrónico a través de [Grupos de Google](https://groups.google.com/a/law.berkeley.edu/g/deportation_data_updates/about) o [por correo electrónico](mailto:deportation_data_updates+subscribe@lists.berkeley.edu).

:::

<div style="height: 1em;"></div>

## Selección de noticias

- [EE.UU.: Abusos de ICE en Los Ángeles sientan precedente para otras ciudades](https://www.hrw.org/news/2025/11/04/us-ice-abuses-in-los-angeles-set-stage-for-other-cities) ([archived](https://web.archive.org/web/20251107191655/https://www.hrw.org/news/2025/11/04/us-ice-abuses-in-los-angeles-set-stage-for-other-cities)), *Human Rights Watch*, 4 de noviembre de 2025 [Inglés]

- [Nuevos datos muestran que 1 de cada 4 arrestos de ICE ocurrieron en Texas bajo la represión migratoria de Trump](https://www.texastribune.org/2025/11/03/texas-trump-immigration-crackdown-ice-arrests-deportation/) ([archived](https://web.archive.org/web/20251104010843/https://www.texastribune.org/2025/11/03/texas-trump-immigration-crackdown-ice-arrests-deportation/)), por Uriel J. García, Colleen DeGuzman, Alex Nguyen y Carla Astudillo, *Texas Tribune*, 3 de noviembre de 2025 [Inglés]

- [El balance: Lo que revelan los datos sobre las órdenes de detención de ICE en Florida](https://suncoastsearchlight.org/the-tally-ice-detainers-in-florida/) ([archived](https://web.archive.org/web/20251107191156/https://suncoastsearchlight.org/the-tally-ice-detainers-in-florida/)), por Kara Newhouse, *Suncoast Searchlight*, 31 de octubre de 2025 [Inglés]

- [Revelado: ICE viola su propia política al retener a personas en salas secretas durante días o semanas](https://www.theguardian.com/us-news/2025/oct/30/ice-hidden-detention-sites) ([archived](https://web.archive.org/web/20251103212350/https://www.theguardian.com/us-news/2025/oct/30/ice-hidden-detention-sites)), por José Olivares y Will Craft, *The Guardian*, 30 de octubre de 2025 [Inglés]

- [Trump recluta un ejército de policías locales para la redada de deportación](https://news.bloomberglaw.com/immigration/trump-marshals-an-army-of-local-cops-for-deportation-dragnet-1), por Michael Smith, Alcicia Caldwell y Myles Miller, *Bloomberg Law*, 28 de octubre de 2025 [Inglés]

- [Cómo la ley estatal de Oklahoma atascada en los tribunales podría impactar la aplicación de leyes de inmigración](https://www.kosu.org/politics/2025-10-23/how-oklahomas-state-law-tied-up-in-the-courts-could-impact-immigration-enforcement) ([archived](https://web.archive.org/web/20251024184516/https://www.kosu.org/politics/2025-10-23/how-oklahomas-state-law-tied-up-in-the-courts-could-impact-immigration-enforcement)), por Lionel Ramos, *KOSU*, 23 de octubre de 2025 [Inglés]

- [Nuevos datos confirman el aumento de arrestos de ICE, leyes más estrictas hacen que permanecer en el país sea una 'batalla cuesta arriba'](https://www.aspenpublicradio.org/2025-10-16/new-data-confirms-that-rising-ice-arrests-and-stricter-laws-make-staying-in-the-country-an-uphill-battle) ([archived](https://web.archive.org/web/20251024003715/https://www.aspenpublicradio.org/2025-10-16/new-data-confirms-that-rising-ice-arrests-and-stricter-laws-make-staying-in-the-country-an-uphill-battle)), por Eleanor Bennett, *Aspen Public Radio*, 16 de octubre de 2025 [Inglés]

- [Una parada de tráfico del NYPD, un ciclomotor sin registrar y 8 meses en un encierro de ICE](https://www.thecity.nyc/2025/10/16/ice-nypd-moped-enforcement-trump-new-york-state/) ([archived](https://web.archive.org/web/20251024003251/https://www.thecity.nyc/2025/10/16/ice-nypd-moped-enforcement-trump-new-york-state/)), por Gwynne Hogan, *The City NYC*, 16 de octubre de 2025 [Inglés]

- [El edificio de ICE en Portland cerró durante 22 días este verano, pero los arrestos y detenciones de inmigración apenas disminuyeron](https://www.opb.org/article/2025/10/15/portland-ice-building-closed-22-days-summer-immigration-arrests-detentions/) ([archived](https://web.archive.org/web/20251024003005/https://www.opb.org/article/2025/10/15/portland-ice-building-closed-22-days-summer-immigration-arrests-detentions/)), por Troy Brynelson y Tony Schick, *Oregon Public Broadcasting*, 15 de octubre de 2025 [Inglés]

- [Los arrestos de ICE en el área de Fresno aumentan en medio de la represión de Trump. Aquí es donde están ocurriendo](https://www.fresnobee.com/news/local/article312445163.html) ([archived](https://web.archive.org/web/20251024002541/https://www.fresnobee.com/news/local/article312445163.html)), por Melissa Montalvo, *Fresno Bee*, 15 de octubre de 2025 [Inglés]

- [Más personas están en detención de inmigración que nunca](https://www.vera.org/news/more-people-are-in-immigration-detention-than-ever-before) ([archived](https://web.archive.org/web/20251009222252/https://www.vera.org/news/more-people-are-in-immigration-detention-than-ever-before)), *Vera Institute of Justice*, 2 de octubre de 2025 [Inglés]

- [ICE detiene a inmigrantes durante largos períodos en el sótano de la oficina local de Atlanta](https://www.ajc.com/news/2025/10/ice-detaining-immigrants-for-long-periods-in-atlanta-field-office-basement/) ([archived](https://web.archive.org/web/20251002225925/https://www.ajc.com/news/2025/10/ice-detaining-immigrants-for-long-periods-in-atlanta-field-office-basement/)), por Lautaro Grinspan y Stephanie Lamm, *Atlanta Journal-Constitution*, 2 de octubre de 2025 [Inglés]

- [Las deportaciones de ICE en California aumentaron un 78% bajo Trump, muestran nuevos datos](https://www.sfchronicle.com/california/article/ice-deported-california-21075519.php) ([archived](https://web.archive.org/web/20251003015608/https://www.sfchronicle.com/california/article/ice-deported-california-21075519.php)), por Christian Leonard, *San Francisco Chronicle*, 30 de septiembre de 2025 [Inglés]

- [Una década de inmigración en Wisconsin en 9 gráficos](https://wisconsinwatch.org/2025/09/a-decade-of-immigration-in-wisconsin-in-9-charts/) ([archived](https://web.archive.org/web/20250929120522/https://wisconsinwatch.org/2025/09/a-decade-of-immigration-in-wisconsin-in-9-charts/)), por Paul Kiefer, *Wisconsin Watch*, 29 de septiembre de 2025 [Inglés]

- [Cómo los detenidos de ICE son trasladados a kilómetros de distancia de sus familias y abogados](https://www.latimes.com/politics/story/2025-09-26/faster-more-frequent-transfers-of-immigrant-ice-detainees-sow-fear-and-cut-off-resources) ([archived](https://web.archive.org/web/20250927022616/https://www.latimes.com/politics/story/2025-09-26/faster-more-frequent-transfers-of-immigrant-ice-detainees-sow-fear-and-cut-off-resources)), por Gabrielle LaMarr LeMee, *Los Angeles Times*, 26 de septiembre de 2025 [Inglés]

- [Cómo se está desarrollando el esfuerzo de deportación de Trump, en gráficos](https://www.wsj.com/us-news/ice-deportations-charts-b3593e29?gaa_at=eafs&gaa_n=ASWzDAhP2t-s3E4NoYpmOvTcGpfuN2yC8qmjJcNWN_nAigmHzFZng1Mwv45KCPDIteU%3D&gaa_ts=68dac32a&gaa_sig=ffiY2jylcRGrF_zzGNzEn9Ms-NnUInmEd879dk4Lsvq6_8-igvKolmqfCp5i1Gq6dzx9LW8Ln_zFWyitcdVnGw%3D%3D) ([archived](https://web.archive.org/web/20250929172053/https://www.wsj.com/us-news/ice-deportations-charts-b3593e29?gaa_at=eafs&gaa_n=ASWzDAhP2t-s3E4NoYpmOvTcGpfuN2yC8qmjJcNWN_nAigmHzFZng1Mwv45KCPDIteU%3D&gaa_ts=68dac32a&gaa_sig=ffiY2jylcRGrF_zzGNzEn9Ms-NnUInmEd879dk4Lsvq6_8-igvKolmqfCp5i1Gq6dzx9LW8Ln_zFWyitcdVnGw%3D%3D)), por Anthony DeBarros, Kara Dapena y Michelle Hackman, *Wall Street Journal*, 25 de septiembre de 2025 [Inglés]

- [Los arrestos del condado de Chatham han llevado a que 124 personas sean liberadas a custodia de ICE en los primeros siete meses](https://www.savannahnow.com/story/news/local/2025/09/23/chatham-county-has-released-124-people-to-ice-in-first-seven-months/85939956007/) ([archived](https://web.archive.org/web/20250923170522/https://www.savannahnow.com/story/news/local/2025/09/23/chatham-county-has-released-124-people-to-ice-in-first-seven-months/85939956007/)), por Ansley Franco, *Savannah Morning News*, 23 de septiembre de 2025 [Inglés]

- [Ella pagó su fianza. ICE se lo llevó. La saga de la familia de Bradenton muestra cómo las cárceles de Florida alimentan las deportaciones](https://www.sarasotamagazine.com/news-and-profiles/2025/09/bradenton-family-ice-deportation) ([archived](https://web.archive.org/web/20250919105047/https://www.sarasotamagazine.com/news-and-profiles/2025/09/bradenton-family-ice-deportation)), por Kara Newhouse y Alice Herman, *Sarasota Magazine*, 19 de septiembre de 2025 [Inglés]

- [ACLU demanda a ICE en San Francisco para detener los arrestos en los tribunales, detención 'inhumana'](https://missionlocal.org/2025/09/sf-aclu-lawsuit-ice-sansome/) ([archived](https://web.archive.org/web/20250922020412/https://missionlocal.org/2025/09/sf-aclu-lawsuit-ice-sansome/)), por Joe Rivano Barros, *Mission Local*, 18 de septiembre de 2025 [Inglés]

- [Nuevo panel de control de aplicación de leyes de inmigración hace que los datos de arrestos de ICE sean más accesibles](https://austinkocher.substack.com/p/new-immigration-enforcement-dashboard) ([archived](https://web.archive.org/web/20250922135256/https://austinkocher.substack.com/p/new-immigration-enforcement-dashboard)), por Austin Kocher, *Substack*, 18 de septiembre de 2025 [Inglés]

- [La ciudad de Portland emitirá notificación de violación de uso de suelo para la instalación de ICE, iniciando proceso para determinar los próximos pasos en el sitio](https://www.portland.gov/mayor/keith-wilson/news/2025/9/17/city-portland-will-issue-land-use-violation-notice-ice-facility) ([archived](https://web.archive.org/web/20250918200813/https://www.portland.gov/mayor/keith-wilson/news/2025/9/17/city-portland-will-issue-land-use-violation-notice-ice-facility)), *City of Portland, Oregon*, 17 de septiembre de 2025 [Inglés]

- [Las detenciones de ICE en cárceles del condado de Nueva York se han disparado](https://nysfocus.com/2025/09/16/ice-detentions-new-york-county-jails) ([archived](https://web.archive.org/web/20250919185323/https://nysfocus.com/2025/09/16/ice-detentions-new-york-county-jails)), por Julia Rock e Isabelle Taft, *New York Focus*, 16 de septiembre de 2025 [Inglés]

- [¿Cuántos inmigrantes ha arrestado y detenido ICE este año? Esto es lo que sabemos](https://chicago.suntimes.com/the-watchdogs/2025/09/12/immigration-customs-enforcement-ice-arrests-detentions-deportation-trac) ([archived](https://web.archive.org/web/20250920185447/https://chicago.suntimes.com/the-watchdogs/2025/09/12/immigration-customs-enforcement-ice-arrests-detentions-deportation-trac)), por Lauren FitzPatrick, *Chicago Sun-Times*, 12 de septiembre de 2025 [Inglés]

- [El centro de deportación de Trump: dentro del 'agujero negro' donde los inmigrantes desaparecen](https://www.theguardian.com/us-news/ng-interactive/2025/sep/12/ice-detention-alexandria-staging-facility) ([archived](https://web.archive.org/web/20250912125456/https://www.theguardian.com/us-news/ng-interactive/2025/sep/12/ice-detention-alexandria-staging-facility)), por Oliver Laughland, Will Craft y Raima Amjad, *The Guardian*, 12 de septiembre de 2025 [Inglés]

- [Avión al purgatorio: cómo el programa de deportación de Trump traslada inmigrantes a un limbo sin ley](https://www.theguardian.com/us-news/ng-interactive/2025/sep/10/trump-globalx-airline-deportation-immigration) ([archived](https://web.archive.org/web/20250910112053/https://www.theguardian.com/us-news/ng-interactive/2025/sep/10/trump-globalx-airline-deportation-immigration)), por Maanvi Singh y Will Craft, *The Guardian*, 10 de septiembre de 2025 [Inglés]

- [Los arrestos de ICE en Virginia se disparan bajo la represión de Trump](https://www.whro.org/virginia-center-for-investigative-journalism/2025-09-09/ice-arrests-in-virginia-soar-under-trump) ([archived](https://web.archive.org/web/20250928212352/https://www.whro.org/virginia-center-for-investigative-journalism/2025-09-09/ice-arrests-in-virginia-soar-under-trump)), por Kunle Falayi, *Virginia Center for Investigative Journalism at WHRO*, 9 de septiembre de 2025 [Inglés]

- [Bajo el gobierno de Trump, ICE elimina el papeleo que los oficiales tenían que hacer antes de los arrestos de inmigración](https://www.nbcnews.com/politics/national-security/trump-administration-ice-scraps-paperwork-officers-immigration-arrests-rcna229407) ([archived](https://web.archive.org/web/20250911112045/https://www.nbcnews.com/politics/national-security/trump-administration-ice-scraps-paperwork-officers-immigration-arrests-rcna229407)), por Julia Ainsley, Didi Martinez y Laura Strickler, *NBC News*, 9 de septiembre de 2025 [Inglés]

- [Los alguaciles locales están convirtiendo sus cárceles en centros de detención de ICE](https://www.nytimes.com/interactive/2025/09/08/us/politics/ice-detention-county-jails-sheriffs-deportation.html) ([archived](https://web.archive.org/web/20250911012357/https://www.nytimes.com/interactive/2025/09/08/us/politics/ice-detention-county-jails-sheriffs-deportation.html)), por Allison McCann, *New York Times*, 8 de septiembre de 2025 [Inglés]

- [Inmigrantes pasan días en 'miserables' salas de espera de ICE, violando política de larga data](https://edition.cnn.com/2025/09/08/us/detainees-ice-immigrants-hold-rooms) ([archived](https://web.archive.org/web/20250908115047/https://edition.cnn.com/2025/09/08/us/detainees-ice-immigrants-hold-rooms)), por Casey Tolan e Isabelle Chapman, *CNN*, 8 de septiembre de 2025 [Inglés]

- [DHS abre nueva instalación de detención de inmigración dentro de la prisión Angola de Luisiana](https://www.cbsnews.com/news/dhs-new-immigration-detention-facility-inside-louisiana-state-penitentiary-angola-prison/) ([archived](https://web.archive.org/web/20250908180603/https://www.cbsnews.com/news/dhs-new-immigration-detention-facility-inside-louisiana-state-penitentiary-angola-prison/)), por Kati Weis y Julia Ingram, *CBS News*, 3 de septiembre de 2025 [Inglés]

- [Mapa: Cómo ICE está utilizando las principales cárceles del condado de Texas para detener inmigrantes](https://www.expressnews.com/projects/2025/texas-ice-detainer-tracker/) ([archived](https://web.archive.org/web/20250912190514/https://www.expressnews.com/projects/2025/texas-ice-detainer-tracker/)), por Yilun Cheng, Matt Zdun y Ava Hu, *San Antonio Express News*, 3 de septiembre de 2025 [Inglés]

- [Los arrestos y deportaciones de inmigración de NYC aumentan después de un inicio lento, muestran datos](https://gothamist.com/news/nyc-immigration-arrests-and-deportations-surge-after-slow-start-data-shows) ([archived](https://web.archive.org/web/20250911093229/https://gothamist.com/news/nyc-immigration-arrests-and-deportations-surge-after-slow-start-data-shows)), por Arya Sundaram, *Gothamist*, 31 de agosto de 2025 [Inglés]

- ['Está sucediendo en todas partes': 1 de cada 3 detenidos de ICE retenido en instalaciones sobrepobladas, muestran datos](https://www.latimes.com/politics/story/2025-08-29/as-ice-detainees-top-60000-some-detention-centers-stack-mattresses-on-the-floor) ([archived](https://web.archive.org/web/20250905010739/https://www.latimes.com/politics/story/2025-08-29/as-ice-detainees-top-60000-some-detention-centers-stack-mattresses-on-the-floor)), por Andrea Castillo y Gabrielle LaMarr LeMee, *Los Angeles Times*, 29 de agosto de 2025 [Inglés]

- [Las deportaciones alcanzan un nuevo máximo después del aumento de verano en los arrestos de inmigración](https://www.nytimes.com/interactive/2025/08/21/us/trump-deportations-summer-data-immigration-arrests.html) ([archived](https://web.archive.org/web/20250831192051/https://www.nytimes.com/interactive/2025/08/21/us/trump-deportations-summer-data-immigration-arrests.html)), por Albert Sun, *New York Times*, 21 de agosto de 2025 [Inglés]

- [Los arrestos de inmigración se quintuplicaron en Denver bajo Trump](https://denverite.com/2025/08/20/denver-immigration-ice-data/) ([archived](https://web.archive.org/web/20250821023511/https://denverite.com/2025/08/20/denver-immigration-ice-data/)), por Kevin Beaty, *Denverite*, 20 de agosto de 2025 [Inglés]

- [Las cárceles de Texas ven un 30% más de órdenes de detención de ICE bajo Trump](https://www.houstonchronicle.com/projects/2025/texas-ice-detainer-tracker/) ([archived](https://web.archive.org/web/20250819155712/https://www.houstonchronicle.com/projects/2025/texas-ice-detainer-tracker/)), por Yilun Cheng, Matt Zdun y Ava Hu, *Houston Chronicle*, 18 de agosto de 2025 [Inglés]

- [ICE está deportando a miles con delitos menores, desde infracciones de tráfico hasta marihuana](https://www.themarshallproject.org/2025/08/15/ice-georgia-traffic-stop-arrest-immigration) ([archived](https://web.archive.org/web/20250823114414/https://www.themarshallproject.org/2025/08/15/ice-georgia-traffic-stop-arrest-immigration)), por Christie Thompson y Anna Flagg, *The Marshall Project*, 15 de agosto de 2025 [Inglés]

- [Migrantes cubanos, más vulnerables que nunca, temen el limbo en Alligator Alcatraz](https://www.miamiherald.com/news/local/immigration/article311668282.html) ([archived](https://web.archive.org/web/20250828175224/https://www.miamiherald.com/news/local/immigration/article311668282.html)), por Shirsho Dasgupta, Ana Ceballos, Ben Wieder, Syra Ortiz Blanes y Ana Claudia Chacin, *Miami Herald*, 15 de agosto de 2025 [Inglés]

- [Orden judicial contra perfilamiento reduce arrestos de ICE en LA en un 66 por ciento](https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order) ([archived](https://web.archive.org/web/20250828175552/https://www.cato.org/blog/anti-profiling-court-order-cuts-la-ice-arrests-66-0)), por David J. Bier, *Cato Institute*, 14 de agosto de 2025 [Inglés]

- [Los arrestos de ICE disminuyen en julio, inmigrantes sin historial criminal siguen siendo el grupo más grande (Parte 5)](https://austinkocher.substack.com/p/ice-arrests-decline-in-july-immigrants) ([archived](https://web.archive.org/web/20250823091618/https://austinkocher.substack.com/p/ice-arrests-decline-in-july-immigrants)), por Austin Kocher, *Substack*, 12 de agosto de 2025 [Inglés]

- [Juez ordena a ICE mejorar condiciones deplorables en el encierro de Manhattan](https://www.thecity.nyc/2025/08/12/judge-trump-federal-immigration-restraining-order-ice/) ([archived](https://web.archive.org/web/20250819225204/https://www.thecity.nyc/2025/08/12/judge-trump-federal-immigration-restraining-order-ice/)), por Gwynne Hogan y Haidee Chu, *The City*, 12 de agosto de 2025 [Inglés]

- [NYC es la capital nacional de arrestos en tribunales de inmigración, muestra nuevo análisis de datos](https://www.thecity.nyc/2025/08/11/26-federal-plaza-immigration-court-trump-arrests-data-analysis/) ([archived](https://web.archive.org/web/20250822042233/https://www.thecity.nyc/2025/08/11/26-federal-plaza-immigration-court-trump-arrests-data-analysis/)), por Haidee Chu y Gwynne Hogan, *The City*, 11 de agosto de 2025 [Inglés]

- [Los ingresos a ICE coinciden estrechamente con los arrestos de inmigración del Proyecto de Datos de Deportación (Parte 4)](https://austinkocher.substack.com/p/ice-book-ins-closely-match-immigration), por Austin Kocher, *Substack*, 8 de agosto de 2025 [Inglés]

- [Uno de cada cinco arrestos de ICE son latinos en las calles sin antecedentes penales ni orden de expulsión](https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order) ([archived](https://web.archive.org/web/20250824062305/https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order)), por David J. Bier, *Cato Institute*, 5 de agosto de 2025 [Inglés]

- [2,123 vidas: Dentro de las estadísticas e historias de quienes fueron arrestados por ICE en el área de San Francisco](https://missionlocal.org/2025/07/ice-data-immigrants-arrested-sf/) ([archived](https://web.archive.org/save/https://missionlocal.org/2025/07/ice-data-immigrants-arrested-sf/)), por Kelly Waldron y Frankie Solinsky Duryea, *Mission Local*, 30 de julio de 2025 [Inglés]

- [Ocultos a plena vista: Cómo las cárceles locales encubren y facilitan la deportación masiva bajo Trump](https://www.prisonpolicy.org/reports/jails_immigration.html) ([archived](https://web.archive.org/save/https://www.prisonpolicy.org/reports/jails_immigration.html)), por Jacob Kang-Brown, *Prison Policy Initiative*, 30 de julio de 2025 [Inglés]

- [El gobierno de Trump planea deportar inmigrantes a terceros países, generando preocupación por derechos humanos](https://theintercept.com/2025/07/29/trump-deport-immigrants-third-country-human-rights/) ([archived](https://web.archive.org/save/https://theintercept.com/2025/07/29/trump-deport-immigrants-third-country-human-rights/)), por Nick Turse, *The Intercept*, 29 de julio de 2025 [Inglés]

- [Trump presume de deportar a “lo peor de lo peor”. Los operativos en Los Ángeles cuentan otra historia muy distinta](https://www.latimes.com/california/story/2025-07-26/trump-deporting-worst-of-worst-reality) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/2025-07-26/trump-deporting-worst-of-worst-reality)), por Jenny Jarvie y Gabrielle LaMarr LeMee, *Los Angeles Times*, 26 de julio de 2025 [Inglés]

- [¿A quién está arrestando ICE? Un análisis basado en datos](https://immresearch.org/publications/who-is-ice-arresting/) ([archived](https://web.archive.org/save/https://immresearch.org/publications/who-is-ice-arresting/)), por Chloe East y Elizabeth Cox, *Immigration Research*, 23 de julio de 2025 [Inglés]

- [Cómo Trump ha sobrealimentado la represión migratoria - en datos](https://www.theguardian.com/us-news/ng-interactive/2025/jul/23/trump-ice-data-deportations-detention) por Maanvi Singh, Will Craft y Andrew Witherspoon, *The Guardian*, 23 de julio de 2025. [Inglés]

- ['Como perros aquí' — Videos exponen encierro del ICE dentro del 26 Federal Plaza](https://www.thecity.nyc/2025/07/22/video-26-federal-plaza-immigration-ice-dhs-cells/) por Gwynne Hogan y Haidee Chu, *The City*, 22 de julio de 2025. [Inglés]



- [Los arrestos de ICE han aumentado considerablemente en todos los estados desde Trump. Estos son los números.](https://www.nytimes.com/interactive/2025/06/27/us/ice-arrests-trump.html), por Albert Sun, *New York Times*, 27 de junio de 2025. [Inglés]

- [Trump dice que está deportando 'lo peor de lo peor'. Esto es lo que realmente muestran los datos de ICE de California](https://www.sfchronicle.com/bayarea/article/ice-arrest-immigrant-california-20395589.php), por Christian Leonard, *San Francisco Chronicle*, 27 de junio de 2025. [Inglés]

- [ICE no dirá cuántas personas ha arrestado en Maine](https://www.bangordailynews.com/2025/06/27/bangor/bangor-police-courts/ice-wont-say-how-many-people-its-arrested-in-maine/), por Marie Weidmayer, *Bangor Daily News*, 27 de junio de 2025. [Inglés]

- [Más de la mitad de los arrestados por ICE en CT tenían cargos criminales pendientes, o condenas](https://www.wfsb.com/2025/06/27/more-than-half-those-arrested-by-ice-ct-had-pending-criminal-charges-or-convictions/), por Sam Smink, *WFSB 3 Connecticut*, 27 de junio de 2025. [Inglés]

- [El fin del sueño americano de Narciso: el brutal arresto de un jardinero mexicano conmociona a Santa Ana](https://english.elpais.com/usa/2025-06-27/the-end-of-narcisos-american-dream-the-brutal-arrest-of-a-mexican-gardener-shocks-santa-ana.html), por Luis Pablo Beauregard, *El País*, 27 de junio de 2025. [Inglés]

- [ICE listo para arrestar un récord de 35,000 inmigrantes en junio, las cuotas diarias son políticas - no prácticas](https://austinkocher.substack.com/p/ice-set-to-arrest-a-record-35000), por Austin Kocher, Substack, 25 de junio de 2025. [Inglés]

- [Nuevos datos muestran que más de la mitad de los detenidos por ICE en Los Ángeles no tienen historial criminal](https://lamag.com/news/new-data-shows-that-over-half-of-those-detained-by-ice-in-los-angeles-have-no-criminal-history), por Ava Mitchell, *Los Angeles Magazine*, 27 de junio de 2025. [Inglés]

- [Obispo católico critica las redadas de ICE, pide reforma migratoria respetuosa](https://premierchristian.news/en/news/article/catholic-bishop-criticises-ice-raids), *Premier Christian News*, 27 de junio de 2025. [Inglés]

- [El 35% de los arrestos de ICE en la ciudad de Nueva York no son criminales, muestran nuevos datos](https://abc7ny.com/post/immigration-enforcement-35-nyc-ice-arrests-arent-criminals-according-newly-released-data/16855965), por Dan Krauth, *ABC7 New York*, 27 de junio de 2025. [Inglés]

- [La Pequeña India de Artesia siente el impacto generalizado de las redadas de inmigración](https://abc7.com/post/artesias-little-india-feels-widespread-impact-immigration-raids/16857210/), por David González, *ABC7 Los Angeles*, 27 de junio de 2025. [Inglés]

- [Líderes asiático-americanos instan a sus comunidades a apoyar a los latinos, denuncian las redadas de ICE](https://www.latimes.com/california/story/2025-06-26/asian-american-leaders-urge-communities-to-stand-by-latinos-denounce-ice-raids) por Melissa Gomez, *Los Angeles Times*, 26 de junio de 2025. [Inglés]

- [La mayoría arrestados por ICE en el área de LA no tienen historial criminal, muestran datos](https://abc7.com/post/more-half-arrested-ice-la-area-have-no-criminal-history-data-shows/16850562/), por Kevin Ozebek, *ABC7 Los Angeles*, 25 de junio de 2025. [Inglés]

- [Una mirada detallada a los datos de arrestos de ICE del Proyecto de Datos de Deportación](https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from?triedRedirect=true), por Austin Kocher, Substack, 25 de junio de 2025. [Inglés]


- [La mayoría capturados en las redadas de LA eran hombres sin condena criminal, recogidos de la calle](https://www.latimes.com/california/story/2025-06-24/detention-centers-swell-with-immigrants-with-no-criminal-record), por Rachel Uranga, *Los Angeles Times*, 24 de junio de 2025. [Inglés]

- [Cómo Trump ha apuntado a nuevos grupos para la deportación](https://www.nytimes.com/interactive/2025/05/21/us/trump-immigration-policy.html) por Ashley Wu y Albert Sun, *New York Times*, 21 de mayo de 2025. [Inglés]

- [Adictos al ICE](https://www.bloomberg.com/features/2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true) por Rachel Adams-Heard, Polly Mosendz y Fola Akinnibi, *Bloomberg* 12 de mayo de 2025. [Inglés]

- [El creciente coste de los vuelos del ICE a centros de detención lejanos](https://www.bloomberg.com/graphics/2025-trump-ice-immigrant-move-costs-taxpayers/?accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb3VyY2UiOiJTdWJzY3JpYmVyR2lmdGVkQXJ0aWNsZSIsImlhdCI6MTc0NjEwNzg1NiwiZXhwIjoxNzQ2NzEyNjU2LCJhcnRpY2xlSWQiOiJTVktYOFNEV1gyUFMwMCIsImJjb25uZWN0SWQiOiJCNTIwMUQ0RjVFMzM0QTNEOEE4QjdDNTBCMkYzNjU4NCJ9.OUyF_xSj6c6TmS_xkDgaDD9zVc0U3_XkmsGyqoyPHjM&leadSource=uverify%20wall) por Leon Yin, Elena Mejía, Rachel Adams-Heard y Polly Mosendz, *Bloomberg* 1 de mayo de 2025. [Inglés]

- [El jefe del ICE cree que el sistema de deportación debería funcionar como Amazon Prime 'pero con seres humanos'](https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html) por Graig Graziosi, *Independent* 9 de abril de 2025. [Inglés]

- [Lo que los datos nos dicen realmente sobre la agenda de deportaciones de Trump](https://www.eltimpano.org/newsletter/what-the-data-really-tells-us-about-trumps-deportation-agenda) por Erica Hellerstein, *El Tímpano* 11 de abril de 2025. [Inglés]

- [A medida que aumentan las deportaciones, los inmigrantes temen cada vez más los controles en el hielo: "Todo está perdido"](https://www.theguardian.com/us-news/2025/apr/06/deportations-immigrants-ice-trump) por Maanvi Singh y Will Craft, *The Guardian* 6 de abril de 2025. [Inglés]

- [Trump promocionó estas detenciones del ICE. La mitad ya estaban en prisión.](https://www.washingtonpost.com/immigration/interactive/2025/trump-ice-arrests-prison-immigrants/) por Maria Sacchetti y Artur Galocha, *Washington Post* 3 de abril de 2025. [Inglés]

- [El ICE liberará al detenido que vino a EE.UU. para donar un riñón a su hermano](https://www.washingtonpost.com/nation/2025/04/02/ice-arrests-venezuelan-kidney-donor/) por Maria Sacchetti, *Washington Post* 2 de abril de 2025. [Inglés]


