---
title: "Data announcements"
toc: false
listing:
  id: news-listings
  contents: news
  sort: "date desc"
  type: table
  fields: [date, title]
  categories: false
  filter-ui: false
  sort-ui: false
---


::: {#news-listings}
:::

::: {.callout-note}
## Subscribe

Subscribe to receive these data updates by email through [Google Groups](https://groups.google.com/a/law.berkeley.edu/g/deportation_data_updates/about) or [by email](mailto:deportation_data_updates+subscribe@lists.berkeley.edu).

:::

<!-- add vertical space -->
<div style="height: 1em;"></div>

## Selected media coverage

* [ICE detaining immigrants for long periods in Atlanta field office basement](https://www.vera.org/news/more-people-are-in-immigration-detention-than-ever-before) ([archived](https://web.archive.org/web/20251009222252/https://www.vera.org/news/more-people-are-in-immigration-detention-than-ever-before)), *Vera Institute of Justice*, October 2, 2025

* [ICE detaining immigrants for long periods in Atlanta field office basement](https://www.ajc.com/news/2025/10/ice-detaining-immigrants-for-long-periods-in-atlanta-field-office-basement/) ([archived](https://web.archive.org/web/20251002225925/https://www.ajc.com/news/2025/10/ice-detaining-immigrants-for-long-periods-in-atlanta-field-office-basement/)), by Lautaro Grinspan and Stephanie Lamm, *Atlanta Journal-Constitution*, October 2, 2025

* [ICE deportations in California are up 78% under Trump, new data shows](https://www.sfchronicle.com/california/article/ice-deported-california-21075519.php) ([archived](https://web.archive.org/web/20251003015608/https://www.sfchronicle.com/california/article/ice-deported-california-21075519.php)), by Christian Leonard, *San Francisco Chronicle*, September 30, 2025

* [A decade of immigration in Wisconsin in 9 charts](https://wisconsinwatch.org/2025/09/a-decade-of-immigration-in-wisconsin-in-9-charts/) ([archived](https://web.archive.org/web/20250929120522/https://wisconsinwatch.org/2025/09/a-decade-of-immigration-in-wisconsin-in-9-charts/)), by Paul Kiefer, *Wisconsin Watch*, September 29, 2025

* [How ICE detainees are moved miles away from their families and attorneys](https://www.latimes.com/politics/story/2025-09-26/faster-more-frequent-transfers-of-immigrant-ice-detainees-sow-fear-and-cut-off-resources) ([archived](https://web.archive.org/web/20250927022616/https://www.latimes.com/politics/story/2025-09-26/faster-more-frequent-transfers-of-immigrant-ice-detainees-sow-fear-and-cut-off-resources)), by Gabrielle LaMarr LeMee, *Los Angeles Times*, September 26, 2025

* [How Trump’s deportation effort is playing out, in charts](https://www.wsj.com/us-news/ice-deportations-charts-b3593e29?gaa_at=eafs&gaa_n=ASWzDAhP2t-s3E4NoYpmOvTcGpfuN2yC8qmjJcNWN_nAigmHzFZng1Mwv45KCPDIteU%3D&gaa_ts=68dac32a&gaa_sig=ffiY2jylcRGrF_zzGNzEn9Ms-NnUInmEd879dk4Lsvq6_8-igvKolmqfCp5i1Gq6dzx9LW8Ln_zFWyitcdVnGw%3D%3D) ([archived](https://web.archive.org/web/20250929172053/https://www.wsj.com/us-news/ice-deportations-charts-b3593e29?gaa_at=eafs&gaa_n=ASWzDAhP2t-s3E4NoYpmOvTcGpfuN2yC8qmjJcNWN_nAigmHzFZng1Mwv45KCPDIteU%3D&gaa_ts=68dac32a&gaa_sig=ffiY2jylcRGrF_zzGNzEn9Ms-NnUInmEd879dk4Lsvq6_8-igvKolmqfCp5i1Gq6dzx9LW8Ln_zFWyitcdVnGw%3D%3D)), by Anthony DeBarros, Kara Dapena and Michelle Hackman, *Wall Street Journal*, September 25, 2025

* [Chatham County arrests have led to 124 people released to ICE custody in first seven months](https://www.savannahnow.com/story/news/local/2025/09/23/chatham-county-has-released-124-people-to-ice-in-first-seven-months/85939956007/) ([archived](https://web.archive.org/web/20250923170522/https://www.savannahnow.com/story/news/local/2025/09/23/chatham-county-has-released-124-people-to-ice-in-first-seven-months/85939956007/)), by Ansley Franco, *Savannah Morning News*, September 23, 2025

* [She paid his bond. ICE took him. Bradenton family’s saga shows how Florida jails fuel deportations](https://www.sarasotamagazine.com/news-and-profiles/2025/09/bradenton-family-ice-deportation) ([archived](https://web.archive.org/web/20250919105047/https://www.sarasotamagazine.com/news-and-profiles/2025/09/bradenton-family-ice-deportation)), by Kara Newhouse and Alice Herman, *Sarasota Magazine*, September 19, 2025

* [ACLU sues ICE in S.F. to stop courthouse arrests, ‘inhumane’ detention](https://missionlocal.org/2025/09/sf-aclu-lawsuit-ice-sansome/) ([archived](https://web.archive.org/web/20250922020412/https://missionlocal.org/2025/09/sf-aclu-lawsuit-ice-sansome/)), by Joe Rivano Barros, *Mission Local*, September 18, 2025

* [New immigration enforcement dashboard makes ICE arrest data accessible to more people](https://austinkocher.substack.com/p/new-immigration-enforcement-dashboard) ([archived](https://web.archive.org/web/20250922135256/https://austinkocher.substack.com/p/new-immigration-enforcement-dashboard)), by Austin Kocher, *Substack*, September 18, 2025

* [City of Portland will issue land use violation notice for ICE facility, triggering process to determine next steps at the site](https://www.portland.gov/mayor/keith-wilson/news/2025/9/17/city-portland-will-issue-land-use-violation-notice-ice-facility) ([archived](https://web.archive.org/web/20250918200813/https://www.portland.gov/mayor/keith-wilson/news/2025/9/17/city-portland-will-issue-land-use-violation-notice-ice-facility)), *City of Portland, Oregon*, September 17, 2025

* [ICE detentions in New York county jails have exploded](https://nysfocus.com/2025/09/16/ice-detentions-new-york-county-jails) ([archived](https://web.archive.org/web/20250919185323/https://nysfocus.com/2025/09/16/ice-detentions-new-york-county-jails)), by Julia Rock and Isabelle Taft, *New York Focus*, September 16, 2025

* [How many immigrants has ICE arrested and detained so far this year? Here's what we know](https://chicago.suntimes.com/the-watchdogs/2025/09/12/immigration-customs-enforcement-ice-arrests-detentions-deportation-trac) ([archived](https://web.archive.org/web/20250920185447/https://chicago.suntimes.com/the-watchdogs/2025/09/12/immigration-customs-enforcement-ice-arrests-detentions-deportation-trac)), by Lauren FitzPatrick, *Chicago Sun-Times*, September 12, 2025

* [Trump’s deportation hub: inside the ‘black hole’ where immigrants disappear](https://www.theguardian.com/us-news/ng-interactive/2025/sep/12/ice-detention-alexandria-staging-facility) ([archived](https://web.archive.org/web/20250912125456/https://www.theguardian.com/us-news/ng-interactive/2025/sep/12/ice-detention-alexandria-staging-facility)), by Oliver Laughland, Will Craft and Raima Amjad, *The Guardian*, September 12, 2025

* [Plane to purgatory: how Trump’s deportation program shuttles immigrants into lawless limbo](https://www.theguardian.com/us-news/ng-interactive/2025/sep/10/trump-globalx-airline-deportation-immigration) ([archived](https://web.archive.org/web/20250910112053/https://www.theguardian.com/us-news/ng-interactive/2025/sep/10/trump-globalx-airline-deportation-immigration)), by Maanvi Singh and Will Craft, *The Guardian*, September 10, 2025

* [ICE arrests in Virginia soar under Trump crackdowns](https://www.whro.org/virginia-center-for-investigative-journalism/2025-09-09/ice-arrests-in-virginia-soar-under-trump) ([archived](https://web.archive.org/web/20250928212352/https://www.whro.org/virginia-center-for-investigative-journalism/2025-09-09/ice-arrests-in-virginia-soar-under-trump)), by Kunle Falayi, *Virginia Center for Investigative Journalism at WHRO*, September 9, 2025

* [Under Trump administration, ICE scraps paperwork officers once had to do before immigration arrests](https://www.nbcnews.com/politics/national-security/trump-administration-ice-scraps-paperwork-officers-immigration-arrests-rcna229407) ([archived](https://web.archive.org/web/20250911112045/https://www.nbcnews.com/politics/national-security/trump-administration-ice-scraps-paperwork-officers-immigration-arrests-rcna229407)), by Julia Ainsley, Didi Martinez and Laura Strickler, *NBC News*, September 9, 2025

* [Local sheriffs are turning their jails into ICE detention centers](https://www.nytimes.com/interactive/2025/09/08/us/politics/ice-detention-county-jails-sheriffs-deportation.html) ([archived](https://web.archive.org/web/20250911012357/https://www.nytimes.com/interactive/2025/09/08/us/politics/ice-detention-county-jails-sheriffs-deportation.html)), by Allison McCann, *New York Times*, September 8, 2025

* [Immigrants spend days in ‘miserable’ ICE hold rooms, violating longstanding policy](https://edition.cnn.com/2025/09/08/us/detainees-ice-immigrants-hold-rooms) ([archived](https://web.archive.org/web/20250908115047/https://edition.cnn.com/2025/09/08/us/detainees-ice-immigrants-hold-rooms)), by Casey Tolan and Isabelle Chapman, *CNN*, September 8, 2025

* [DHS opens new immigration detention facility inside Louisiana's Angola prison](https://www.cbsnews.com/news/dhs-new-immigration-detention-facility-inside-louisiana-state-penitentiary-angola-prison/) ([archived](https://web.archive.org/web/20250908180603/https://www.cbsnews.com/news/dhs-new-immigration-detention-facility-inside-louisiana-state-penitentiary-angola-prison/)), by Kati Weis and Julia Ingram, *CBS News*, September 3, 2025

* [Map: How ICE is using major Texas county jails to detain immigrants](https://www.expressnews.com/projects/2025/texas-ice-detainer-tracker/) ([archived](https://web.archive.org/web/20250912190514/https://www.expressnews.com/projects/2025/texas-ice-detainer-tracker/)), by Yilun Cheng, Matt Zdun and Ava Hu, *San Antonio Express News*, September 3, 2025

* [NYC immigration arrests and deportations surge after slow start, data shows](https://gothamist.com/news/nyc-immigration-arrests-and-deportations-surge-after-slow-start-data-shows) ([archived](https://web.archive.org/web/20250911093229/https://gothamist.com/news/nyc-immigration-arrests-and-deportations-surge-after-slow-start-data-shows)), by Arya Sundaram, *Gothamist*, August 31, 2025

* [‘It’s happening everywhere’: 1 in 3 ICE detainees held in overcrowded facilities, data show](https://www.latimes.com/politics/story/2025-08-29/as-ice-detainees-top-60000-some-detention-centers-stack-mattresses-on-the-floor) ([archived](https://web.archive.org/web/20250905010739/https://www.latimes.com/politics/story/2025-08-29/as-ice-detainees-top-60000-some-detention-centers-stack-mattresses-on-the-floor)), by Andrea Castillo and Gabrielle LaMarr LeMee, *Los Angeles Times*, August 29, 2025

* [Deportations reach new high after summer surge in immigration arrests](https://www.nytimes.com/interactive/2025/08/21/us/trump-deportations-summer-data-immigration-arrests.html) ([archived](https://web.archive.org/web/20250831192051/https://www.nytimes.com/interactive/2025/08/21/us/trump-deportations-summer-data-immigration-arrests.html)), by Albert Sun, *New York Times*, August 21, 2025

* [Immigration arrests have quintupled in Denver under Trump](https://denverite.com/2025/08/20/denver-immigration-ice-data/) ([archived](https://web.archive.org/web/20250821023511/https://denverite.com/2025/08/20/denver-immigration-ice-data/)), by Kevin Beaty, *Denverite*, August 20, 2025

* [Texas jails see 30% more ICE holds under Trump.](https://www.houstonchronicle.com/projects/2025/texas-ice-detainer-tracker/) ([archived](https://web.archive.org/web/20250819155712/https://www.houstonchronicle.com/projects/2025/texas-ice-detainer-tracker/)), by Yilun Cheng, Matt Zdun and Ava Hu, *Houston Chronicle*, August 18, 2025

* [ICE is deporting 1000s with minor offenses from traffic violations to weed](https://www.themarshallproject.org/2025/08/15/ice-georgia-traffic-stop-arrest-immigration) ([archived](https://web.archive.org/web/20250823114414/https://www.themarshallproject.org/2025/08/15/ice-georgia-traffic-stop-arrest-immigration)), by Christie Thompson and Anna Flagg, *The Marshall Project*, August 15, 2025

* [Cuban migrants, more vulnerable than ever, fear limbo at Alligator Alcatraz](https://www.miamiherald.com/news/local/immigration/article311668282.html) ([archived](https://web.archive.org/web/20250828175224/https://www.miamiherald.com/news/local/immigration/article311668282.html)), by Shirsho Dasgupta, Ana Ceballos, Ben Wieder, Syra Ortiz Blanes and Ana Claudia Chacin, *Miami Herald*, August 15, 2025

* [Anti-profiling court order cuts LA ICE arrests by 66 percent](https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order) ([archived](https://web.archive.org/web/20250828175552/https://www.cato.org/blog/anti-profiling-court-order-cuts-la-ice-arrests-66-0)), by David J. Bier, *Cato Institute*, August 14, 2025

* [ICE arrests decline in July, immigrants with no criminal history still largest group (Part 5)](https://austinkocher.substack.com/p/ice-arrests-decline-in-july-immigrants) ([archived](https://web.archive.org/web/20250823091618/https://austinkocher.substack.com/p/ice-arrests-decline-in-july-immigrants)), by Austin Kocher, *Substack*, August 12, 2025

* [Judge orders ICE to improve squalid Manhattan lockup conditions](https://www.thecity.nyc/2025/08/12/judge-trump-federal-immigration-restraining-order-ice/) ([archived](https://web.archive.org/web/20250819225204/https://www.thecity.nyc/2025/08/12/judge-trump-federal-immigration-restraining-order-ice/)), by Gwynne Hogan and Haidee Chu, *The City*, August 12, 2025

* [NYC is the nation’s capital of immigration courthouse arrests, new data analysis shows](https://www.thecity.nyc/2025/08/11/26-federal-plaza-immigration-court-trump-arrests-data-analysis/) ([archived](https://web.archive.org/web/20250822042233/https://www.thecity.nyc/2025/08/11/26-federal-plaza-immigration-court-trump-arrests-data-analysis/)), by Haidee Chu and Gwynne Hogan, *The City*, August 11, 2025

* [ICE book-ins closely match immigration arrests from Deportation Data Project (Part 4)](https://austinkocher.substack.com/p/ice-book-ins-closely-match-immigration), by Austin Kocher, *Substack*, August 8, 2025

* [One in five ICE arrests are Latinos on the streets with no criminal past or removal order](https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order) ([archived](https://web.archive.org/web/20250824062305/https://www.cato.org/blog/1/5-ice-arrests-are-latinos-streets-no-criminal-past-or-removal-order)), by David J. Bier, *Cato Institute*, August 5, 2025

* [2,123 lives: inside the stats and stories of those arrested by ICE from the S.F. area](https://missionlocal.org/2025/07/ice-data-immigrants-arrested-sf/) ([archived](https://web.archive.org/save/https://missionlocal.org/2025/07/ice-data-immigrants-arrested-sf/)), by Kelly Waldron and Frankie Solinsky Duryea, *Mission Local*, July 30, 2025

* [Hiding in plain sight: How local jails obscure and facilitate mass deportation under Trump](https://www.prisonpolicy.org/reports/jails_immigration.html) ([archived](https://web.archive.org/save/https://www.prisonpolicy.org/reports/jails_immigration.html)), by Jacob Kang-Brown, *Prison Policy Initiative*, July 30, 2025

* [Trump administration plans to deport immigrants to third countries, raising human rights concerns](https://theintercept.com/2025/07/29/trump-deport-immigrants-third-country-human-rights/) ([archived](https://web.archive.org/save/https://theintercept.com/2025/07/29/trump-deport-immigrants-third-country-human-rights/)), by Nick Turse, *The Intercept*, July 29, 2025

* [Trump boasts of deporting the ‘worst of the worst.’ L.A. raids tell a far different story](https://www.latimes.com/california/story/2025-07-26/trump-deporting-worst-of-worst-reality) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/2025-07-26/trump-deporting-worst-of-worst-reality)), by Jenny Jarvie and Gabrielle LaMarr LeMee, *Los Angeles Times*, July 26, 2025

* [Who is ICE arresting? A data-driven analysis](https://immresearch.org/publications/who-is-ice-arresting/) ([archived](https://web.archive.org/save/https://immresearch.org/publications/who-is-ice-arresting/)), by Chloe East and Elizabeth Cox, *Immigration Research*, July 23, 2025

* [How Trump has supercharged the immigration crackdown - in data](https://www.theguardian.com/us-news/ng-interactive/2025/jul/23/trump-ice-data-deportations-detention) ([archived](https://web.archive.org/save/https://www.theguardian.com/us-news/ng-interactive/2025/jul/23/trump-ice-data-deportations-detention)), by Maanvi Singh, Will Craft and Andrew Witherspoon, *The Guardian*, July 23, 2025

* ['Like Dogs in Here' — Videos expose ICE lock-up inside 26 Federal Plaza](https://www.thecity.nyc/2025/07/22/video-26-federal-plaza-immigration-ice-dhs-cells/) ([archived](https://web.archive.org/save/https://www.thecity.nyc/2025/07/22/video-26-federal-plaza-immigration-ice-dhs-cells/)), by Gwynne Hogan and Haidee Chu, *The City*, July 22, 2025

* [ICE’s child catching in charts](https://www.ft.com/content/d8a2071c-b106-4458-bb41-6e654c679218), by Robin Wigglesworth, *Financial Times*, July 17, 2025

* [Inside America’s booming immigration detention industry](https://ig.ft.com/us-immigration-detention/), by Lucy Rodgers, Nassos Stylianou, Irene de la Torre Arenas, Jana Tauschinski, Sam Learner, Daniel Clark, Sam Joiner and Gaku Ito, *Financial Times*, July 15, 2025

* [ICE arrests surge in May and June driven by immigrants with no criminal history (Part 3)](https://austinkocher.substack.com/p/ice-arrest-surge-in-may-and-june) ([archived](https://web.archive.org/web/20250824164106/https://austinkocher.substack.com/p/ice-arrest-surge-in-may-and-june)), by Austin Kocher, *Substack*, July 15, 2025

* [ICE increasingly targets undocumented migrants with no criminal record](https://www.washingtonpost.com/immigration/2025/07/03/ice-arrests-migrants-criminal-record-numbers/) ([archived](https://web.archive.org/save/https://www.washingtonpost.com/immigration/2025/07/03/ice-arrests-migrants-criminal-record-numbers/)), by Emmanuel Martinez, Marianne LeVine and Álvaro Valiño, *The Washington Post*, July 3, 2025

* [Sharpest growth in ICE detention population is among people with no criminal convictions](https://www.npr.org/2025/07/03/nx-s1-5454891/sharpest-growth-in-ice-detention-population-people-with-no-criminal-convictions) ([archived](https://web.archive.org/save/https://www.npr.org/2025/07/03/nx-s1-5454891/sharpest-growth-in-ice-detention-population-people-with-no-criminal-convictions)), by Jasmine Garsd, *NPR*, July 3, 2025

* [Immigration crackdown ripples through economy](https://www.axios.com/2025/07/02/trump-immigration-crackdown-economy) ([archived](https://web.archive.org/save/https://www.axios.com/2025/07/02/trump-immigration-crackdown-economy)), by Emily Peck, *Axios*, July 2, 2025

* [Trump vowed to deport the ‘worst of the worst’ — but new data shows a shift to also arresting non-criminals](https://abcnews.go.com/US/trump-vowed-deport-worst-worst-new-data-shows/story?id=123287810) ([archived](https://web.archive.org/save/https://abcnews.go.com/US/trump-vowed-deport-worst-worst-new-data-shows/story?id=123287810)), by Laura Romero, Armando Garcia and Frank Esposito, *ABC News*, July 1, 2025

* [ICE detentions of non-criminal immigrants spike; about 8 % have violent convictions, analysis shows](https://www.cbsnews.com/news/ice-detentions-non-criminal-immigrants-violent-crime-convictions-analysis/) ([archived](https://web.archive.org/save/https://www.cbsnews.com/news/ice-detentions-non-criminal-immigrants-violent-crime-convictions-analysis/)), by Julia Ingram, *CBS News*, June 30, 2025

* [‘It’s a prison’: Asylum seekers in Houston detention centers face longer stays, no clear answers](https://www.houstonchronicle.com/news/houston-texas/immigration/article/houston-asylum-seekers-face-longer-detention-ice-20381512.php) ([archived](https://web.archive.org/save/https://www.houstonchronicle.com/news/houston-texas/immigration/article/houston-asylum-seekers-face-longer-detention-ice-20381512.php)), by Sam González Kelly and Ava Hu, *Houston Chronicle*, June 29, 2025

* [ICE arrests have risen sharply in every state since Trump. Here are the numbers.](https://www.nytimes.com/interactive/2025/06/27/us/ice-arrests-trump.html) ([archived](https://web.archive.org/save/https://www.nytimes.com/interactive/2025/06/27/us/ice-arrests-trump.html)), by Albert Sun, *The New York Times*, June 27, 2025

* [ICE set to arrest a record 35,000 immigrants in June; daily quotas are political – not practical (Part 2)](https://austinkocher.substack.com/p/ice-set-to-arrest-a-record-35000) ([archived](https://web.archive.org/save/https://austinkocher.substack.com/p/ice-set-to-arrest-a-record-35000)), by Austin Kocher, *Substack*, June 25, 2025

* [A close look at ICE arrest data from the Deportation Data Project (Part 1)](https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from?triedRedirect=true) ([archived](https://web.archive.org/save/https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from?triedRedirect=true)), by Austin Kocher, *Substack*, June 25, 2025

* [Most nabbed in L.A. raids were men with no criminal conviction, picked up off the street](https://www.latimes.com/california/story/2025-06-24/detention-centers-swell-with-immigrants-with-no-criminal-record) ([archived](https://web.archive.org/save/https://www.latimes.com/california/story/2025-06-24/detention-centers-swell-with-immigrants-with-no-criminal-record)), by Rachel Uranga, *Los Angeles Times*, June 24, 2025

* [How Trump has targeted new groups for deportation](https://www.nytimes.com/interactive/2025/05/21/us/trump-immigration-policy.html) ([archived](https://web.archive.org/save/https://www.nytimes.com/interactive/2025/05/21/us/trump-immigration-policy.html)), by Ashley Wu and Albert Sun, *The New York Times*, May 21, 2025

* [Addicted to ICE](https://www.bloomberg.com/features/2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true) ([archived](https://web.archive.org/save/https://www.bloomberg.com/features/2025-addicted-to-ice-immigrant-detention-centers/?embedded-checkout=true)), by Rachel Adams-Heard, Polly Mosendz and Fola Akinnibi, *Bloomberg*, May 12, 2025

* [The rising cost of ICE flying immigrants to far-flung detention centers](https://www.bloomberg.com/graphics/2025-trump-ice-immigrant-move-costs-taxpayers/) ([archived](https://web.archive.org/save/https://www.bloomberg.com/graphics/2025-trump-ice-immigrant-move-costs-taxpayers/)), by Leon Yin, Elena Mejía, Rachel Adams-Heard and Polly Mosendz, *Bloomberg*, May 1, 2025

* [ICE chief thinks deportation system should be run like Amazon Prime ‘but with human beings’](https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html) ([archived](https://web.archive.org/save/https://www.independent.co.uk/news/world/americas/us-politics/ice-deportations-amazon-prime-b2730464.html)), by Graig Graziosi, *The Independent*, April 9, 2025

* [As deportations ramp up, immigrants increasingly fear ICE check-ins: ‘All bets are off’](https://www.theguardian.com/us-news/2025/apr/06/deportations-immigrants-ice-trump) ([archived](https://web.archive.org/save/https://www.theguardian.com/us-news/2025/apr/06/deportations-immigrants-ice-trump)), by Maanvi Singh and Will Craft, *The Guardian*, April 6, 2025

* [Trump touted these ICE arrests. Half were already in prison.](https://www.washingtonpost.com/immigration/interactive/2025/trump-ice-arrests-prison-immigrants/) ([archived](https://web.archive.org/save/https://www.washingtonpost.com/immigration/interactive/2025/trump-ice-arrests-prison-immigrants/)), by Maria Sacchetti and Artur Galocha, *The Washington Post*, April 3, 2025
