---
title: "ICE data release: Sep. 2023 to early June 2025"
subtitle: "Second ICE Data Release Under New Administration"
date: "6/21/2025" # make sure to change date
---

The Deportation Data Project has obtained a new release of nationwide, individual-level Immigration and Customs Enforcement (ICE) data, now covering more than four months of the second Trump administration, along with about a year and a half of the end of the Biden administration. The anonymized dataset contains detailed information on encounters, arrests, detainers, and detentions.
 
The new dataset, like the one released in March, was obtained through a FOIA lawsuit against ICE brought by the UCLA Center for Immigration Law and Policy, represented by Lieff Cabraser Heimann & Bernstein LLP and Amber Qureshi of the Deportation Data Project. The dataset includes anonymized identifiers that correspond to individuals, allowing users to follow individuals through the enforcement process without learning their identities. 

In addition to the new data, we released documentation that [describes the data from ICE](/docs/ice.html) as well as from [Customs and Border Protection](/docs/cbp.html) and the [Executive Office for Immigration Review (EOIR)](/docs/eoir.html). The documentation includes a codebook describing the data tables available from each agency, the variables included in each table, as well as any public documentation of the data obtained from or published by the agencies.