---
title: "ICE data release: Sep. 2023 to late June 2025"
subtitle: "Third ICE Data Release Under New Administration"
date: "7/14/2025" # make sure to change date
---

The Deportation Data Project has obtained a new release of nationwide, individual-level Immigration and Customs Enforcement (ICE) data, now covering the period from September 1, 2023 to June 26, 2025. The new dataset covers sixteen more days than the previous (early June) release. Unfortunately, as in the previous release, the removals dataset only includes records from Jan. 1, 2025 onward because the records from before Jan. 1, 2025 appeared to have significant errors. 

The new dataset, like the ones released in March and June, was obtained through a FOIA lawsuit against ICE brought by the UCLA Center for Immigration Law and Policy, represented by Lieff Cabraser Heimann & Bernstein LLP and Amber Qureshi of the Deportation Data Project. The dataset includes anonymized identifiers that correspond to individuals, allowing users to follow individuals through the enforcement process without learning their identities.
