---
title: "Data repository"
subtitle: "Office of Homeland Security Statistics"
toc-expand: 2
---

```{r}
library(tidyverse)
library(reactable)

col_defs <- list(
  Start = colDef(minWidth = 75),
  End = colDef(minWidth = 75),
  Records = colDef(minWidth = 55, align = "right"),
  Source = colDef(minWidth = 65, html = TRUE),
  Download = colDef(minWidth = 100, html = TRUE)
)

options(
  reactable.theme = reactableTheme(
    backgroundColor = "#F4F6F7"
  )
)
```

### Immigration Enforcement and Legal Processes Monthly Tables

Through January 2025, the Office of Homeland Security Statistics released a monthly spreadsheet tracking a variety of actions by both CBP and ICE. We do not know whether to expect future releases.

```{r}
enf_files <-
  tibble::tribble(
          ~Date,                                                                                               ~Source,                                                                                                                                                           ~Download,
    "Jan. 2025",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836538278882'>xlsx</a> (712 kB)",
    "Dec. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836538669625'>xlsx</a> (671 kB)",
    "Nov. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836532468031'>xlsx</a> (668 kB)",
    "Oct. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836522683414'>xlsx</a> (678 kB)",
    "Sep. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836537352654'>xlsx</a> (673 kB)",
    "Aug. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836538234805'>xlsx</a> (669 kB)",
    "Jul. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836534182041'>xlsx</a> (666 kB)",
    "Jun. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836521399297'>xlsx</a> (653 kB)",
    "May. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836532585571'>xlsx</a> (644 kB)",
    "Apr. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836535261459'>xlsx</a> (478 kB)",
    "Mar. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836530651460'>xlsx</a> (406 kB)",
    "Feb. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836524668163'>xlsx</a> (407 kB)",
    "Jan. 2024",   "<a href='https://ohss.dhs.gov/topics/immigration/immigration-enforcement/monthly-tables'>OHSS</a>",   "<a href='https://ucla.app.box.com/index.php?rm=box_download_shared_file&shared_name=9d8qnnduhus4bd5mwqt7l95kz34fic2v&file_id=f_1836536929304'>xlsx</a> (401 kB)"
  )
```

```{r}
enf_files |>
  slice(1) |>
  reactable::reactable(
    columns = list(
      Date = colDef(align = "left"),
      Source = colDef(minWidth = 65, html = TRUE),
      Download = colDef(minWidth = 100, html = TRUE)
    ),
    pagination = FALSE
  )
```

<div style="margin-top: 0.5em;"></div>

<details>
<summary>Past reports</summary>

```{r}
enf_files |>
  slice(-1) |>
  reactable::reactable(
    columns = list(
      Date = colDef(align = "left"),
      Source = colDef(minWidth = 65, html = TRUE),
      Download = colDef(minWidth = 100, html = TRUE)
    ),
    pagination = FALSE
  )
```

</details>

