---
title: "Report repository"
---

```{r}
library(tidyverse)
library(reactable)

col_defs <- list(
  Start = colDef(minWidth = 75),
  End = colDef(minWidth = 75),
  Records = colDef(minWidth = 55, align = "right"),
  Source = colDef(minWidth = 65, html = TRUE),
  Download = colDef(minWidth = 100, html = TRUE)
)

options(
  reactable.theme = reactableTheme(
    backgroundColor = "#F4F6F7"
  )
)
```

Our project's focus is on collecting and posting individual-level data, but this page is an exception: here, we collect and repost government reports that draw from the individual-level datasets we post. We hope that this centralized repository of reports (and links to government websites) will help users of the individual-level data.  

The reports come from the Office of Homeland Security Statistics (OHSS), Immigration and Customs Enforcement (ICE), Customs and Border Protection (CBP), and the Executive Office of Immigration Review (EOIR). These reports are generally available for download from the government directly; we repost them for users' convenience. The original source is always a government agency (OHSS, ICE, CBP, or EOIR), but where other third parties have posted the reports before we have, we link to their sites as the source.

## Customs and Border Protection 


## Executive Office for Immigration Review<br>(Immigration Courts)


## Immigration and Customs Enforcement

## Office of Homeland Security Statistics

