---
title: "Data documentation from CBP"
---

```{r}
library(tidyverse)
library(reactable)
library(glue)

options(
  reactable.theme = reactableTheme(
    backgroundColor = "#F4F6F7"
  )
)

# Store the data frame to access in cell functions
library(googlesheets4)
gs4_deauth()
doc_data <- read_sheet(
  "https://docs.google.com/spreadsheets/d/1Acckm7h-Hs690Tv6bvtKEg_9L2yITqp0QqN5hN2dhWw/edit?gid=0#gid=0"
)
```

```{r}

# Store filtered data once at the top level
filtered_doc_data <- doc_data |>
  filter(Agency == "DHS CBP", is.na(exclude)) |>
  mutate(Date = as.Date(Date)) |>
  select(Type, Title, Agency, Date, Link, Contributor)

filtered_doc_data |>
  reactable(
    columns = list(
      Type = colDef(),
      Title = colDef(
        name = "Document",
        cell = function(value, index) {
          url <- filtered_doc_data$Link[index]
          if (is.null(url) || is.na(url) || url == "" || length(url) == 0) {
            return(value)
          }
          htmltools::tags$a(href = url, target = "_blank", value)
        }
      ),
      Date = colDef(
        name = "Date",
        cell = function(value) {
          if (is.na(value)) {
            return("")
          }
          month_abbr <- format(value, "%b")
          day_year <- format(value, "%e, %Y")
          if (nchar(month_abbr) == 3) {
            paste0(month_abbr, ". ", day_year)
          } else {
            paste0(month_abbr, " ", day_year)
          }
        }
      ), # Add comma here
      Link = colDef(
        name = "Source",
        cell = function(value, index) {
          agency <- filtered_doc_data$Agency[index]

          if (
            is.null(value) || is.na(value) || value == "" || length(value) == 0
          ) {
            return("")
          }

          htmltools::tags$a(href = value, target = "_blank", agency)
        }
      ),
      Contributor = colDef(
        name = "Contributor",
        # make cell say em dash if it's NA
        cell = function(value) {
          if (
            is.null(value) || is.na(value) || value == "" || length(value) == 0
          ) {
            return("—")
          }
          value
        }
      ),
      Agency = colDef(show = FALSE)
    )
  )
```