---
title: "CBP data documentation"
toc: false
---

We post four datasets from CBP on our [data page](/data/cbp.html). Below we describe each table.

```{r}
library(reactable)
library(tidyverse)

tibble::tribble(
  ~Name,
  ~Description,
  "Apprehensions at the border",
  "This dataset includes every apprehension at the border. Before 2020, all border arrests were apprehensions, and these files therefore include all arrests for those years. With the onset of the Title 42 pandemic expulsions program, some border arrests led to expulsions, which CBP does not categorize as apprehensions.",
  "People deemed inadmissible at ports of entry",
  "This dataset includes records of each person CBP found inadmissible at a port of entry. These are mostly asylum seekers.",
  "Title 42 expulsions",
  "This dataset includes Title 42 expulsions: the border arrests that CBP does not categorize as apprehensions.",
  "Encounters",
  "This dataset includes all border arrests, both apprehensions and Title 42 expulsions. Notice, however, that it exists currently only for a relatively short period.",
  "Annual apprehensions with place of origin",
  "This dataset includes each person’s city and state of origin, but it lacks precise dates for each apprehension (it shows only the fiscal year), limiting its use. The file names suggest that these files only contain family apprehensions, but they actually contain all apprehensions."
) |>
  arrange(Name) |>
  reactable(
    columns = list(
      Name = colDef(minWidth = 100),
      Description = colDef(minWidth = 200, sortable = FALSE)
    ), # set id anchor for linking
    pagination = FALSE,
    striped = TRUE,
    fullWidth = TRUE,
    theme = reactableTheme(
      # clear the table itself
      tableStyle = list(backgroundColor = "transparent"),
      # keep the cells transparent too
      headerStyle = list(backgroundColor = "transparent")
    )
  )
```

We are in the process of collecting documentation for data regularly provided by CBP. For now, we include documentation from CBP below.

- [Inadmissibles data disposition code dictionary](https://ucla.box.com/shared/static/lhnuflx0nreiqapxvoi7zl0yan1u03g2.pdf)



```{r}
library(tidyverse)
library(reactable)
library(glue)

options(
  reactable.theme = reactableTheme(
    backgroundColor = "#F4F6F7"
  )
)

# Store the data frame to access in cell functions
library(googlesheets4)
gs4_deauth()
doc_data <- read_sheet(
  "https://docs.google.com/spreadsheets/d/1Acckm7h-Hs690Tv6bvtKEg_9L2yITqp0QqN5hN2dhWw/edit?gid=0#gid=0"
)

doc_data |>
  filter(Agency == "CBP") |>
  select(Title, Description, Date, Contributor) |>
  mutate(Date = as.Date(Date) |> as.character()) |>
  reactable(
    columns = list(
      Title = colDef(
        name = "Document",
        cell = function(value, index) {
          url <- doc_data$Filename[index]
          if (is.null(url) || is.na(url) || url == "") {
            return(value)
          }
          htmltools::tags$a(href = url, target = "_blank", value)
        }
      ),
      Date = colDef(
        name = "Date"
      ),
      Contributor = colDef(
        name = "Source",
        cell = function(value, index) {
          source_url <- "test" #doc_data$source_url[index]
          if (is.null(source_url) || is.na(source_url) || source_url == "") {
            return(value)
          }
          htmltools::tags$a(href = source_url, target = "_blank", value)
        }
      )
    )
  )
```