---
title: "Documentación de datos de ICE"
# author:
#   - name: Proyecto de Datos de Deportación
#     url: "https://deportationdata.org"
#   - name: "Centro de Derechos Humanos de la Universidad de Washington"
#     url: "https://jsis.washington.edu/humanrights"
---

```{r}
library(reactable)
library(tidyverse)

library(googlesheets4)
gs4_deauth()

# Define the URL of the Google Sheets document
url <- "https://docs.google.com/spreadsheets/d/1LD4WSEHNRwnTxIY6I9eau2VOqonOL0_MOhnIwknyzHQ/edit?gid=0#gid=0"
# Read the data from the Google Sheets document
tables <- read_sheet(url, sheet = "tables")
fields <- read_sheet(url, sheet = "fields_edited")
values <- read_sheet(url, sheet = "values", col_types = "c")
missingness_df <- read_rds("../missingness_by_field.rds")
```

ICE recopila datos sobre cada persona que encuentra, arresta, detiene, transporta por vuelo y deporta.

A continuación publicamos los datos que ICE elaboró en respuesta a varias solicitudes de FOIA presentadas por múltiples organizaciones. Es crucial que, en algunas publicaciones de datos, existan identificadores vinculados entre tipos de datos como arrestos y órdenes de detención, lo que permite fusiones que permiten rastrear las trayectorias de los inmigrantes (de forma anónima) a través del sistema de aplicación de la ley de inmigración. Desafortunadamente, los identificadores son diferentes entre publicaciones, solo permitiendo fusiones dentro de una misma publicación de datos. 

::: {.callout-tip appearance="simple"}

## Cómo empezar con los datos de ICE

* Nuestras [preguntas frecuentes sobre los datos de ICE](/docs/ice.html#faq) son un buen lugar para empezar antes de analizar los datos.
* También proporcionamos un [libro de códigos (en inglés)](https://deportationdata.org/docs/ice/codebook.html) que describe cada tabla de datos y los campos contenidos en ellas. (En Inglés solamente por ahora; lo sentimos).

:::


### Preguntas frecuentes sobre los datos de ICE {#faq}

<div style="margin-bottom: 2rem;"></div>

::: {#ice-faq .accordion .accordion-flush}

:::: {.accordion-item}
::::: {.accordion-header #heading-q1}
<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q1" aria-expanded="true" aria-controls="collapse-q1">¿Qué datos de ICE ha publicado el Proyecto de Datos de Deportación?</button>
:::::
::::: {#collapse-q1 .accordion-collapse .collapse .show aria-labelledby="heading-q1" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Hemos publicado datos a nivel individual sobre: arrestos, también llamados aprehensiones; órdenes de detención, que son solicitudes que ICE hace a cárceles locales y prisiones para retener individuos para transferirlos a la custodia de ICE; detenciones, que son registros de individuos retenidos bajo custodia de ICE; encuentros, que son registros de individuos con quienes ICE se encontró en persona o buscó electrónicamente; y expulsiones, que son registros de deportaciones realizadas por ICE.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q2}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q2" aria-expanded="false" aria-controls="collapse-q2">¿Qué son datos a nivel individual?</button>
:::::
::::: {#collapse-q2 .accordion-collapse .collapse aria-labelledby="heading-q2" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Buscamos y publicamos datos que están a nivel individual. Eso significa que los conjuntos de datos contienen una fila para cada acción individual de aplicación de la ley de inmigración (como arresto o deportación). Esto permite al usuario realizar análisis--por ejemplo, contar el número de arrestos que ocurrieron en un área determinada de responsabilidad. Nosotros no realizamos análisis por nosotros mismos (aunque esperamos tener la capacidad de hacerlo en el futuro). Eso significa que no proporcionamos conteos, reportes o estadísticas resumidas. En cambio, si ve conteos o estadísticas resumidas atribuidas al Proyecto de Datos de Deportación, eso significa que alguien descargó datos de nuestro sitio web y los usó para realizar análisis.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q3}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q3" aria-expanded="false" aria-controls="collapse-q3">¿De dónde provienen los datos de ICE?</button>
:::::
::::: {#collapse-q3 .accordion-collapse .collapse aria-labelledby="heading-q3" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Los datos provienen del propio ICE en respuesta a solicitudes de FOIA. En la mayoría de los casos, proporcionamos los datos sin procesar que ICE proporcionó sin modificación. Anotamos cada vez en que hemos modificado los datos, tal como para hacer posible abrirlos.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q3b}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q3b" aria-expanded="false" aria-controls="collapse-q3b">¿Cómo obtuvo el Proyecto de Datos de Deportación estos datos?</button>
:::::
::::: {#collapse-q3b .accordion-collapse .collapse aria-labelledby="heading-q3b" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Obtuvimos estos datos a través de una [solicitud](https://deportationdata.org/foia/cilp-v-ice-2024/1%20FOIA%20request.pdf) de la Ley de Libertad de Información presentada por el Centro para la Ley y Política de Inmigración con nuestra asistencia. Después de que ICE no respondiera a la solicitud durante seis meses, CILP presentó una [demanda](https://deportationdata.org/foia/cilp-v-ice-2024/2%20District%20Court%20Complaint.pdf) en el Tribunal de Distrito de los Estados Unidos para el Distrito Central de California en diciembre de 2024 para obligar la divulgación de los datos. CILP está representado en el litigio por miembros de nuestro equipo. La primera publicación de datos bajo *CILP v ICE* fue producida por ICE en marzo de 2025, y hasta la fecha hemos recibido tres actualizaciones más a principios de junio, finales de junio y finales de julio.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q4}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q4" aria-expanded="false" aria-controls="collapse-q4">¿Cómo debo citar los datos de ICE del Proyecto de Datos de Deportación?</button>
:::::
::::: {#collapse-q4 .accordion-collapse .collapse aria-labelledby="heading-q4" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Recomendamos: "datos gubernamentales proporcionados por ICE en respuesta a una solicitud de FOIA al Proyecto de Datos de Deportación y analizados por [su organización]."

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q5}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q5" aria-expanded="false" aria-controls="collapse-q5">¿Cuándo actualizarán estos conjuntos de datos?</button>
:::::
::::: {#collapse-q5 .accordion-collapse .collapse aria-labelledby="heading-q5" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Publicamos rápidamente los datos que recibimos de ICE, pero ICE no ha acordado publicar estos conjuntos de datos en ningún cronograma, por lo que es imposible predecir cuándo, o en qué intervalos, recibiremos actualizaciones. Buscamos activamente actualizaciones.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q6}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q6" aria-expanded="false" aria-controls="collapse-q6">¿Cómo puedo acceder a los datos?</button>
:::::
::::: {#collapse-q6 .accordion-collapse .collapse aria-labelledby="heading-q6" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Puede acceder a los datos en las tablas a continuación. Cada tabla tiene una columna "Descargar" con un enlace para descargar los datos como un archivo de Excel. La publicación más reciente también está disponible como un archivo ZIP con todas las tablas juntas. Puede abrirlos directamente en Microsoft Excel u otro programa de hoja de cálculo o leerlos en un software estadístico como R o Stata.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q7}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q7" aria-expanded="false" aria-controls="collapse-q7">¿Tienen un diccionario de datos o libro de códigos?</button>
:::::
::::: {#collapse-q7 .accordion-collapse .collapse aria-labelledby="heading-q7" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Sí, compilamos lo que sabemos sobre los datos de ICE en un [libro de códigos](https://deportationdata.org/docs/ice/codebook.html). Nuestro entendimiento es muy incompleto. Más generalmente, nuestra [guía de datos](https://deportationdata.org/guide.html) proporciona una visión general de los datos de aplicación de la ley de inmigración de Estados Unidos en todo el gobierno.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q8}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q8" aria-expanded="false" aria-controls="collapse-q8">¿Puedo filtrar los datos de arrestos por mi estado, ciudad o vecindario?</button>
:::::
::::: {#collapse-q8 .accordion-collapse .collapse aria-labelledby="heading-q8" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Sí, pero de manera imperfecta. Tres variables (columnas) pueden ser útiles: "Área de Responsabilidad", "Punto de Referencia" y "Estado". Cada una es útil, pero también incompleta. La variable de estado es precisa, pero a veces falta. La variable Área de Responsabilidad, que representa el área de cobertura de una oficina local de ICE, es geográficamente amplia; algunas áreas abarcan regiones muy grandes. ICE proporciona [alguna información](https://www.ice.gov/contact/field-offices?office=16) sobre las áreas de cobertura. El Punto de Referencia se refiere a un lugar cerca del arresto y a veces es el más específico geográficamente, pero [se usa de manera inconsistente](https://uwchr.github.io/ice-enforce/landmarks.html).

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q9}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q9" aria-expanded="false" aria-controls="collapse-q9">Vi su advertencia sobre los datos de remociones. ¿Cómo puedo obtener la mejor imagen de las deportaciones?</button>
:::::
::::: {#collapse-q9 .accordion-collapse .collapse aria-labelledby="heading-q9" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Anteriormente no publicamos los datos de remociones en la publicación de ICE de finales de julio. Lea [por qué publicamos el conjunto de datos](/news/2025-09-29-update-ICE-removals.html) y ahora creemos que está completo.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q10}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q10" aria-expanded="false" aria-controls="collapse-q10">Noté que hay algunos duplicados en los datos de arrestos. ¿Cómo debo considerarlos?</button>
:::::
::::: {#collapse-q10 .accordion-collapse .collapse aria-labelledby="heading-q10" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Ningún enfoque debería cambiar las estimaciones dramáticamente, ya que solo cerca del 5% de las filas involucran posibles duplicados. Hay varios tipos de posibles duplicados en los datos y múltiples enfoques razonables para resolverlos. Primero, hay 38 duplicados en todos los campos (donde el identificador único no falta). Estos 38 parecen claramente ser duplicados y pueden eliminarse. Segundo, hay cerca de 6,000 filas que involucran más de un arresto de la misma persona en la misma fecha de aprehensión. Es menos claro si estos son duplicados o reflejan arrestos repetidos reales en el mismo día, lo que parece improbable pero concebible. Tres tipos en particular vale la pena mencionar. Primero, muchos de los duplicados involucran una fila con un estado de caso que dice "E-Charging Document Canceled by ICE"; estos parecen probablemente ser duplicados, pero no siempre está claro qué fila retener, ya que en algunos casos la fila con el estado "E-Charging Document Canceled by ICE" incluye más información (es decir, a veces esa fila incluye un punto de referencia de aprehensión, mientras que la otra fila para la misma persona no). Segundo, muchas filas son idénticas en todos los campos aparte de la marca de tiempo; para estas filas, pensamos que sería razonable elegir solo la fila posterior. Tercero, muchas filas no sólo tienen fechas e IDs únicos idénticos, sino también marcas de tiempo idénticas. También parece seguro asumir que estos son duplicados. En resumen, hay varias formas de filtrar duplicados, y las elecciones correctas no son obvias. Afortunadamente, ninguna elección debería llevar a grandes diferencias en las estimaciones.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q11}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q11" aria-expanded="false" aria-controls="collapse-q11">¿Cómo puedo identificar arrestos en tribunales en los datos?</button>
:::::
::::: {#collapse-q11 .accordion-collapse .collapse aria-labelledby="heading-q11" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Desafortunadamente, no conocemos una buena manera de identificar arrestos en tribunales.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q12}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q12" aria-expanded="false" aria-controls="collapse-q12">¿Cómo puedo identificar redadas en comunidades en los datos, en oposición a arrestos en citas programadas o en una cárcel o prisión?</button>
:::::
::::: {#collapse-q12 .accordion-collapse .collapse aria-labelledby="heading-q12" data-bs-parent="#ice-faq"}
<div class="accordion-body">

No es posible aislar completamente los arrestos que tienen lugar en comunidades (en oposición a dentro de cárceles o prisiones, por ejemplo). Sin embargo, hay dos indicadores que pueden ser útiles: en la tabla de arrestos cuando el "Método de Aprehensión" es "Localizado" o "Arresto No Custodial", pensamos que estos registros tienen más probabilidades de indicar arrestos en la comunidad.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q13}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q13" aria-expanded="false" aria-controls="collapse-q13">¿Cómo puedo saber si las órdenes de detención son respetadas por las cárceles locales y estatales y las prisiones?</button>
:::::
::::: {#collapse-q13 .accordion-collapse .collapse aria-labelledby="heading-q13" data-bs-parent="#ice-faq"}
<div class="accordion-body">

No parece haber ninguna manera de determinar a partir de estos datos si una cárcel o prisión está reteniendo a individuos por hasta 48 horas en respuesta a una solicitud de orden de detención. Sin embargo, hay formas de determinar si un individuo es ingresado a la detención de ICE después de una solicitud de orden de detención. El campo "Razón de Levantamiento de Orden de Detención" en la tabla de órdenes de detención incluye valores que probablemente representan rechazos de órdenes de detención ("Orden de Detención Rechazada por LEA") y algunos que pueden representar aceptación de órdenes de detención ("Ingresado a Detención"). Sin embargo, ese campo frecuentemente falta. Si el campo falta, puede significar que la persona permanece en custodia criminal, la orden de detención no fue respetada, o que ICE aún no ha actualizado el registro para indicar si fue respetada. Una segunda manera de confirmar si el individuo fue transferido a custodia de ICE después de una solicitud de orden de detención es unir la tabla de órdenes de detención con la tabla de detenciones por ID único. Si el ID único en la tabla de órdenes de detención no aparece en la tabla de detenciones, es posible que la orden de detención no fue respetada. Sin embargo, note que el individuo aún puede estar en custodia criminal. Si el ID único sí aparece en la tabla de detenciones, eso significa que el individuo fue ingresado a custodia de ICE después de una solicitud de orden de detención.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q14}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q14" aria-expanded="false" aria-controls="collapse-q14">¿Incluyen estos datos todos los arrestos, detenciones y remociones de inmigración del gobierno de Estados Unidos?</button>
:::::
::::: {#collapse-q14 .accordion-collapse .collapse aria-labelledby="heading-q14" data-bs-parent="#ice-faq"}
<div class="accordion-body">

No, solo incluyen acciones de Operaciones de Aplicación y Remoción de ICE (ERO). ICE ERO es generalmente responsable de arrestos civiles de inmigración en el interior de Estados Unidos, lejos de las fronteras internacionales (el [Substack de Austin Kocher discute](https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from) los datos de arrestos de ICE en detalle). La Oficina de Aduanas y Protección Fronteriza (CBP) realiza arrestos y detenciones en o cerca de la frontera. Algunas personas arrestadas por CBP son transferidas para detención y remoción por ICE. CBP también niega la entrada y remueve a personas consideradas inadmisibles en la frontera. Publicamos [datos de CBP](https://deportationdata.org/data/cbp.html) sobre arrestos (encuentros) y personas consideradas inadmisibles en la frontera. CBP no ha publicado datos tan recientemente como ICE.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q15}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q15" aria-expanded="false" aria-controls="collapse-q15">¿Cómo puedo identificar remociones a terceros países?</button>
:::::
::::: {#collapse-q15 .accordion-collapse .collapse aria-labelledby="heading-q15" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Cada tabla tiene una columna para "País de Salida", que indica a dónde fueron removidos los individuos. Para identificar remociones a terceros países en las que un no ciudadano fue deportado a un país distinto a su país de ciudadanía, compare esos países con la columna "País de Ciudadanía" y/o la columna "País de Nacimiento". El "País de Ciudadanía" puede no incluir todas las nacionalidades en el caso de ciudadanía dual y, como con todos los datos, son posibles errores.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q16}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q16" aria-expanded="false" aria-controls="collapse-q16">¿Por qué cambiarían los datos para el mismo individuo entre publicaciones?</button>
:::::
::::: {#collapse-q16 .accordion-collapse .collapse aria-labelledby="heading-q16" data-bs-parent="#ice-faq"}
<div class="accordion-body">

ICE parece actualizar registros retroactivamente en un número relativamente pequeño de casos, incluyendo cambiar las tablas de arrestos, encuentros, órdenes de detención y detenciones cuando tiene lugar una remoción. Esto puede resultar en patrones ligeramente diferentes en períodos superpuestos de dos publicaciones de datos. No sabemos si hay un horario o procedimiento sistemático que dicte cuándo ocurren estas actualizaciones.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q17}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q17" aria-expanded="false" aria-controls="collapse-q17">¿Por qué hay muchas filas por persona en la tabla de detención?</button>
:::::
::::: {#collapse-q17 .accordion-collapse .collapse aria-labelledby="heading-q17" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Cada fila en la tabla de detenciones representa tiempo en una instalación de detención específica desde el ingreso hasta la salida. Una persona arrestada por ICE podría ser transferida a múltiples instalaciones durante su detención, representada en múltiples filas. En general, ICE se refiere a todo el período de detención (desde el ingreso a la primera detención hasta la salida del último centro de detención) como una "estadía". Una estadía a menudo incluye múltiples ingresos a diferentes centros de detención, y una persona (identificada anónimamente por ID único) puede tener múltiples estadías (si es liberada de detención y luego detenida nuevamente). Vea nuestro [libro de códigos de ICE](https://deportationdata.org/docs/ice/codebook.html) para mayor explicación de los datos de detenciones.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q18}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q18" aria-expanded="false" aria-controls="collapse-q18">¿Por qué parece que los datos faltan arrestos/encuentros/órdenes de detención/detenciones/remociones para algunos meses?</button>
:::::
::::: {#collapse-q18 .accordion-collapse .collapse aria-labelledby="heading-q18" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Algunas de las hojas de cálculo están divididas en múltiples hojas. Las hojas deben apilarse antes de ser analizadas.

</div>
:::::
::::

:::
