---
title: "ICE data documentation"
toc: false
sidebar: "ICE Documentation"
---

::: {.grid}

::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi clipboard-data class="me-2" >}} Codebook

Description of the tables and fields (variables) in the ICE data on administrative arrests, detainers, detentions, encounters, and removals.

[Read](/docs/ice/codebook.html){.btn-action-primary .btn-action .btn .btn-outline-primary .btn-sm role="button"} 

:::

<!--
::: {.g-col-12 .g-col-md-4 .g-col-lg-4}

### {{< bi file-earmark-text class="me-2" >}} Documents

Documentation from the government about ICE data, posted on their website or obtained via FOIA.

[Explore](mailto:deportation_data_questions@law.berkeley.edu){.btn .btn-outline-primary .btn-sm role="button"} 

:::

-->

:::


### Frequently asked questions about the ICE data {#faq}

<div style="margin-bottom: 2rem;"></div>

::: {#ice-faq .accordion .accordion-flush}

:::: {.accordion-item}
::::: {.accordion-header #heading-q1}
<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q1" aria-expanded="true" aria-controls="collapse-q1">What ICE data has the Deportation Data Project posted?</button>
:::::
::::: {#collapse-q1 .accordion-collapse .collapse .show aria-labelledby="heading-q1" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We have posted individual-level data on: arrests, also called apprehensions; detainers, which are requests that ICE makes to local jails and prisons to hold individuals for transfer to ICE custody; detentions, which are records of individuals held in ICE custody; encounters, which are records of individuals who ICE either encountered in person or searched for electronically; and removals, which are records of deportations conducted by ICE.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q2}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q2" aria-expanded="false" aria-controls="collapse-q2">What is individual-level data?</button>
:::::
::::: {#collapse-q2 .accordion-collapse .collapse aria-labelledby="heading-q2" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We seek and post data that is at the individual level. That means the datasets contain a row for each individual immigration enforcement action (such as arrest or removal). This allows the user to conduct analysis--for example, to count the number of arrests that occurred in a given area of responsibility. We do not conduct analysis ourselves (although we hope to have the capacity to do so in the future). That means that we do not provide counts, reports, or summary statistics. Instead, if you see counts or summary statistics attributed to the Deportation Data Project, that means someone downloaded data from our website and used it to conduct analysis.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q3}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q3" aria-expanded="false" aria-controls="collapse-q3">Where does the ICE data come from?</button>
:::::
::::: {#collapse-q3 .accordion-collapse .collapse aria-labelledby="heading-q3" data-bs-parent="#ice-faq"}
<div class="accordion-body">

The data comes from ICE itself in response to FOIA requests. In most cases, we provide the raw data ICE provided without modification. We note any time we have modified the data, such as to make it possible to open.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q3b}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q3b" aria-expanded="false" aria-controls="collapse-q3b">How did the Deportation Data Project obtain these data?</button>
:::::
::::: {#collapse-q3b .accordion-collapse .collapse aria-labelledby="heading-q3b" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We obtained these data through a Freedom of Information Act [request](https://deportationdata.org/foia/cilp-v-ice-2024/1%20FOIA%20request.pdf) filed by the Center for Immigration Law and Policy with our assistance. After ICE did not respond to the request for six months, CILP filed a [lawsuit](https://deportationdata.org/foia/cilp-v-ice-2024/2%20District%20Court%20Complaint.pdf) in the U.S. District Court for the Central District of California in December 2024 to compel the release of the data. CILP is represented in the litigation by members of our team. The first data release under *CILP v ICE* was produced by ICE in March 2025, and to date we have received three more updates in early June, late June, and late July.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q4}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q4" aria-expanded="false" aria-controls="collapse-q4">How should I cite ICE data from the Deportation Data Project?</button>
:::::
::::: {#collapse-q4 .accordion-collapse .collapse aria-labelledby="heading-q4" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We recommend: "government data provided by ICE in response to a FOIA request to the Deportation Data Project and analyzed by [your organization]."

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q5}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q5" aria-expanded="false" aria-controls="collapse-q5">When will you update these datasets?</button>
:::::
::::: {#collapse-q5 .accordion-collapse .collapse aria-labelledby="heading-q5" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We promptly post data that we receive from ICE, but ICE has not agreed to release these datasets on any schedule, so it is impossible to predict when, or at what intervals, we will receive updates. We are actively seeking updates.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q6}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q6" aria-expanded="false" aria-controls="collapse-q6">How can I access the data?</button>
:::::
::::: {#collapse-q6 .accordion-collapse .collapse aria-labelledby="heading-q6" data-bs-parent="#ice-faq"}
<div class="accordion-body">

You can access the data in the tables below. Each table has a "Download" column with a link to download the data as an Excel file. The most recent release is also available as a ZIP file with all of the tables together. You can open them directly in Microsoft Excel or another spreadsheet program or read them into a statistical software such as R or Stata.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q7}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q7" aria-expanded="false" aria-controls="collapse-q7">Do you have a data dictionary or codebook?</button>
:::::
::::: {#collapse-q7 .accordion-collapse .collapse aria-labelledby="heading-q7" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Yes, we compiled what we know about the ICE data in a [codebook](https://deportationdata.org/docs/ice/codebook.html). Our understanding is very incomplete. More generally, our [data guide](https://deportationdata.org/guide.html) provides an overview of US immigration enforcement data across the government.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q8}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q8" aria-expanded="false" aria-controls="collapse-q8">Can I filter arrests data to my state, city, or neighborhood?</button>
:::::
::::: {#collapse-q8 .accordion-collapse .collapse aria-labelledby="heading-q8" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Yes, but imperfectly. Three variables (columns) may be useful: "Area of Responsibility," "Landmark," and "State." Each is useful, but also incomplete. The state variable is accurate, but sometimes missing. The Area of Responsibility variable, which represents the coverage area of an ICE field office, is geographically coarse; some areas encompass very large regions. ICE provides [some information](https://www.ice.gov/contact/field-offices?office=16) on the coverage areas. The Landmark refers to a place near the arrest and is sometimes the most geographically-specific, but [it is inconsistently used](https://uwchr.github.io/ice-enforce/landmarks.html).

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q9}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q9" aria-expanded="false" aria-controls="collapse-q9">I saw your warning about removals data. How can I get the best picture of deportations?</button>
:::::
::::: {#collapse-q9 .accordion-collapse .collapse aria-labelledby="heading-q9" data-bs-parent="#ice-faq"}
<div class="accordion-body">

We did not receive correct removals data in our latest release (for late July). If you are interested in analyzing removals for the first half of 2025, we recommend using the removals data from late June 2025 (covering only the period beginning in January 2025). Unfortunately, we believe the removals data we posted in the previous, early June 2025, release was incomplete, even with respect to the period it covered. We did not post removals data at all in the late February or late July releases due to apparent errors. In each case (again with the exception of the 2025 data from late June 2025), we discovered many fewer removals in the data provided than in other publicly available sources. These concerns lead us to advise caution when performing any analysis of removals.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q10}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q10" aria-expanded="false" aria-controls="collapse-q10">I noticed that there are some duplicates in the arrests data. How should I account for those?</button>
:::::
::::: {#collapse-q10 .accordion-collapse .collapse aria-labelledby="heading-q10" data-bs-parent="#ice-faq"}
<div class="accordion-body">

No approach should change estimates dramatically, since only about 5% of rows involve potential duplicates.  There are several types of potential duplicates in the data and multiple reasonable approaches to resolving them. First, there are 38 duplicates across all fields (where the unique identifier is not missing). These 38 seem clearly to be duplicates and can be dropped. Second, there are close to 6,000 rows involving more than one arrest of the same individual on the same apprehension date. It is less clear whether these are duplicates or reflect actual repeated arrests on the same day, which seems unlikely but conceivable. Three types in particular are worth mentioning. First, many of the duplicates involve a row with a case status that reads "E-Charging Document Canceled by ICE"; these seem likely to be duplicates, but it's not always clear which row to retain, since in some cases the row with the "E-Charging Document Canceled by ICE" status includes more information (i.e. sometimes that row includes an apprehension landmark, whereas the other row for the same person does not). Second, many rows are identical across all fields apart from the time stamp; for these rows, we think it would be reasonable to choose just the later row. Third, many rows have not only identical dates and unique IDs, but also identical times stamps. It also seems safe to assume that these are duplicates. In sum, there are several ways to screen for duplicates, and correct choices are not obvious. Luckily, no choice should lead to large differences in estimates.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q11}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q11" aria-expanded="false" aria-controls="collapse-q11">How can I identify courtroom arrests in the data?</button>
:::::
::::: {#collapse-q11 .accordion-collapse .collapse aria-labelledby="heading-q11" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Unfortunately we do not know of a good way to identify arrests at courthouses. 

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q12}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q12" aria-expanded="false" aria-controls="collapse-q12">How can I identify raids in communities in the data, as opposed to arrests at check-ins or a jail or prison?</button>
:::::
::::: {#collapse-q12 .accordion-collapse .collapse aria-labelledby="heading-q12" data-bs-parent="#ice-faq"}
<div class="accordion-body">

It is not possible to fully isolate arrests that take place in communities (as opposed to within jails or prisons, for example). However, there are two indicators that may be useful: in the arrests table when "Apprehension Method" is "Located" or "Non-Custodial Arrest" we think that these records are more likely to indicate arrests in the community.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q13}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q13" aria-expanded="false" aria-controls="collapse-q13">How can I tell whether detainers are honored by local and state jails and prisons?</button>
:::::
::::: {#collapse-q13 .accordion-collapse .collapse aria-labelledby="heading-q13" data-bs-parent="#ice-faq"}
<div class="accordion-body">

There does not appear to be any way to determine from these data whether a jail or prison is holding individuals for up to 48 hours in response to a detainer request. However, there are ways to determine whether an individual is booked into ICE detention following a detainer request. The "Detainer Lift Reason" field in the detainers table includes values that likely represent detainer refusals ("Detainer Declined by LEA") and some that may represent accepting detainers ("Booked into Detention"). However, that field is often missing. If the field is missing, it may mean that the person remains in criminal custody, the detainer was not honored, or that ICE has not yet updated the record to indicate whether it was honored. A second way to confirm whether the individual was transferred to ICE custody following a detainer request is to join the detainers table to the detentions table by unique ID. If the unique ID in the detainers table does not appear in the detentions table, it is possible that the detainer was not honored. Note, however, that the individual may still be in criminal custody. If the unique ID does appear in the detentions table, that means the individual was booked into ICE custody following a detainer request.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q14}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q14" aria-expanded="false" aria-controls="collapse-q14">Do these data include all immigration arrests, detentions, and removals by the US government?</button>
:::::
::::: {#collapse-q14 .accordion-collapse .collapse aria-labelledby="heading-q14" data-bs-parent="#ice-faq"}
<div class="accordion-body">

No, they only include actions by ICE Enforcement and Removal Operations (ERO). ICE ERO is generally responsible for civil immigration arrests in the interior of the United States, away from international borders (Austin Kocher’s [Substack discusses](https://austinkocher.substack.com/p/a-close-look-at-ice-arrest-data-from) the ICE arrests data in detail). Customs and Border Protection (CBP) conducts arrests and detentions at or near the border. Some people arrested by CBP are transferred for detention and removal by ICE. CBP also refuses entry and removes people deemed inadmissible at the border. We post [data from CBP](https://deportationdata.org/data/cbp.html) on arrests (encounters) and people deemed inadmissible at the border. CBP has not released data as recently as ICE has. 

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q15}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q15" aria-expanded="false" aria-controls="collapse-q15">How can I identify removals to third countries?</button>
:::::
::::: {#collapse-q15 .accordion-collapse .collapse aria-labelledby="heading-q15" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Every table has a column for "Departed Country," which indicates where individuals were removed to. To identify third-country removals in which a noncitizen was deported to a country other than their country of citizenship, compare those countries to the "Citizenship Country" and/or the "Birth Country" column. The "Citizenship Country" may not include all nationalities in the case of dual citizenship and, as with all data, errors are possible.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q16}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q16" aria-expanded="false" aria-controls="collapse-q16">Why would data for the same individual change between releases?</button>
:::::
::::: {#collapse-q16 .accordion-collapse .collapse aria-labelledby="heading-q16" data-bs-parent="#ice-faq"}
<div class="accordion-body">

ICE appears to update records retroactively in a relatively small number of cases, including by changing the arrests, encounters, detainers, and detentions tables when a removal takes place. This may result in slightly different patterns in overlapping periods of two data releases. We do not know whether there is a schedule or systematic procedure dictating when these updates occur.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q17}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q17" aria-expanded="false" aria-controls="collapse-q17">Why are there many rows per person in the detention table?</button>
:::::
::::: {#collapse-q17 .accordion-collapse .collapse aria-labelledby="heading-q17" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Each row in the detentions table represents time in a specific detention facility from book-in to book-out. A person arrested by ICE might be transferred to multiple facilities during their detention, represented in multiple rows. Overall, ICE refers to the whole detention period (from book-in to the first detention to book-out from the last detention center) as a “stay.” A stay often includes multiple book-ins to different detention centers,  and one person (identified anonymously by unique ID) can have multiple stays (if released from detention and later detained again). See our [ICE codebook](https://deportationdata.org/docs/ice.html) for further explanation of the detentions data.

</div>
:::::
::::

:::: {.accordion-item}
::::: {.accordion-header #heading-q18}
<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-q18" aria-expanded="false" aria-controls="collapse-q18">Why does it appear that the data is missing arrests/encounters/detainers/detentions/removals for some months?</button>
:::::
::::: {#collapse-q18 .accordion-collapse .collapse aria-labelledby="heading-q18" data-bs-parent="#ice-faq"}
<div class="accordion-body">

Some of the spreadsheets are split over multiple sheets. The sheets should be stacked before being analyzed.

</div>
:::::
::::

:::