name: Update news from Google News RSS

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  pull_request:
  workflow_dispatch:

jobs:
  check-rss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse", "xml2", "rvest"))'

      - name: Check RSS Feed
        run: |
          Rscript scripts/get_news.R

      - name: Commit if new items
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add news_feed.json
          git diff --cached --quiet || git commit -m 'Update RSS feed items'
          git push