name: Test Link Checker (Dry Run)

on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: read

jobs:
  test-link-checker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install lychee
        run: |
          curl -L https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin/
          chmod +x /usr/local/bin/lychee
          echo "✅ Lychee installed successfully"
      
      - name: Set up GitHub CLI
        run: |
          # GitHub CLI is pre-installed on ubuntu-latest runners
          gh --version
          echo "✅ GitHub CLI is available"
      
      - name: Test lychee installation
        run: |
          lychee --version
          echo "✅ Lychee is working correctly"
      
      - name: Test script execution (dry run)
        run: |
          echo '{"url": "https://example.com/broken", "source": "https://example.com/page", "status": "broken", "error": "404 Not Found"}' > /tmp/test_results.json
          export GITHUB_REPOSITORY="test/test"
          export GITHUB_TOKEN="fake_token"
          bash .github/scripts/create-issues.sh /tmp/test_results.json || echo "Expected failure - no valid GitHub token in test"
          echo "✅ Issue creation script processes input correctly"
      
      - name: Test workflow file syntax
        run: |
          python -c "
          import yaml
          with open('.github/workflows/check-links.yml', 'r') as f:
              yaml.safe_load(f)
          print('✅ Workflow YAML syntax is valid')
          "
      
      - name: Test shell script syntax
        run: |
          bash -n .github/scripts/check-links.sh
          bash -n .github/scripts/create-issues.sh
          echo "✅ Shell script syntax is valid"