name: Test Link Checker (Dry Run)

on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: read

jobs:
  test-link-checker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install muffet
        run: |
          wget -O muffet.tar.gz https://github.com/raviqqe/muffet/releases/download/v2.10.3/muffet_linux_amd64.tar.gz
          tar -xzf muffet.tar.gz
          sudo mv muffet /usr/local/bin/
          chmod +x /usr/local/bin/muffet
          echo "✅ Muffet installed successfully"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          pip install requests
      
      - name: Validate Python script syntax
        run: |
          python -m py_compile .github/scripts/create-issues.py
          echo "✅ Python script syntax is valid"
      
      - name: Test muffet installation
        run: |
          muffet --version
          echo "✅ Muffet is working correctly"
      
      - name: Test script execution (dry run)
        run: |
          echo '{"url": "https://example.com/broken", "source": "https://example.com/page", "error": "404 Not Found"}' > /tmp/test_results.json
          python .github/scripts/create-issues.py /tmp/test_results.json || echo "Expected failure - no GitHub token in test"
          echo "✅ Issue creation script processes input correctly"
      
      - name: Test workflow file syntax
        run: |
          python -c "
          import yaml
          with open('.github/workflows/check-links.yml', 'r') as f:
              yaml.safe_load(f)
          print('✅ Workflow YAML syntax is valid')
          "
      
      - name: Test shell script syntax
        run: |
          bash -n .github/scripts/check-links.sh
          echo "✅ Shell script syntax is valid"